//! Byte-exact replay of a recorded session (docs/impl-plan.md, Phase 1 gate 1).
//!
//! Skipped unless `LOWLAT_CORPUS` points at a recording directory, so
//! continuous integration, which has no corpus, is unaffected. The corpus
//! carries a live session key and therefore lives outside the repository.
//!
//! Four assertions, in increasing scope, so a failure localises instead of
//! saying "mismatch":
//!
//! 1. Decrypting a wire record reproduces its paired cleartext record.
//!    Isolates the envelope and the cipher.
//! 2. Every cleartext record parses. Isolates the packet layer.
//! 3. Re-encoding a parsed packet reproduces the recorded bytes. Isolates
//!    header emission.
//! 4. Message spans match the length prefix and end on the last-fragment flag.
//!    Isolates the framing arithmetic.
//! 5. Real receive rings reassemble the same messages, and their contents
//!    parse as the media they claim to be. Isolates the ring and the
//!    reassembler.

use std::collections::HashMap;
use std::fs::File;
use std::io::{BufReader, Read};
use std::path::{Path, PathBuf};

use lowlat_core::channel::{RecvRing, SlotMeta, Stored};
use lowlat_core::envelope::{Cipher, Envelope};
use lowlat_core::message;
use lowlat_core::packet::{self, Packet};
use lowlat_core::session::Session;
use lowlat_core::{control, init, video};

const MAGIC: &[u8; 8] = b"P2PWIRE1";
const STAGE_WIRE: u8 = 0;
const STAGE_CLEARTEXT: u8 = 1;

struct Recording {
    key: Vec<u8>,
    cipher: Cipher,
    body_capacity: usize,
}

/// Pull one string or number field out of a flat JSON object.
///
/// A hand parser rather than a dependency: the file is flat, generated by us,
/// and pulling in a JSON stack for four fields is not worth it.
fn field<'a>(text: &'a str, key: &str) -> Option<&'a str> {
    let needle = format!("\"{key}\"");
    let rest = &text[text.find(&needle)? + needle.len()..];
    let rest = rest.trim_start().strip_prefix(':')?.trim_start();
    if let Some(rest) = rest.strip_prefix('"') {
        let end = rest.find('"')?;
        Some(&rest[..end])
    } else {
        let end = rest.find([',', '\n', '}'])?;
        Some(rest[..end].trim())
    }
}

fn unhex(text: &str) -> Option<Vec<u8>> {
    if text.len() % 2 != 0 {
        return None;
    }
    (0..text.len() / 2)
        .map(|i| u8::from_str_radix(text.get(i * 2..i * 2 + 2)?, 16).ok())
        .collect()
}

fn load_session(dir: &Path) -> Recording {
    let text = std::fs::read_to_string(dir.join("session.json")).expect("session.json");
    let cipher = match field(&text, "cipher").expect("cipher") {
        "aes256" => Cipher::Aes256,
        "aes128" => Cipher::Aes128,
        other => panic!("unknown cipher {other}"),
    };
    let key = unhex(field(&text, "key_hex").expect("key_hex")).expect("key_hex is hex");
    // The recorded value is the cleartext size; the body budget is what is left
    // after the packet header.
    let mtu: usize = field(&text, "mtu")
        .and_then(|v| v.parse().ok())
        .unwrap_or(1200);
    Recording {
        key,
        cipher,
        body_capacity: mtu - packet::HEADER_LEN,
    }
}

struct Record {
    dir: u8,
    stage: u8,
    t_us: u64,
    data: Vec<u8>,
}

fn read_record(reader: &mut impl Read) -> Option<Record> {
    let mut head = [0u8; 16];
    match reader.read_exact(&mut head) {
        Ok(()) => {}
        Err(_) => return None,
    }
    let len = u32::from_le_bytes([head[12], head[13], head[14], head[15]]) as usize;
    let mut data = vec![0u8; len];
    reader.read_exact(&mut data).ok()?;
    let t_us = u64::from_le_bytes([
        head[4], head[5], head[6], head[7], head[8], head[9], head[10], head[11],
    ]);
    Some(Record {
        dir: head[0],
        stage: head[1],
        t_us,
        data,
    })
}

/// Per-direction, per-channel message tracker.
#[derive(Default)]
struct Framing {
    expected_seq: Option<u32>,
    remaining: usize,
    declared: usize,
    collected: usize,
}

#[derive(Default)]
struct Counts {
    wire: u64,
    cleartext: u64,
    data: u64,
    acks: u64,
    messages_validated: u64,
    resyncs: u64,
    retransmits: u64,
    reassembled: u64,
    control_messages: u64,
    video_messages: u64,
    /// Recorded video messages whose header we re-emitted byte for byte.
    video_reemitted: u64,
    keyframes: u64,
}

#[test]
fn replays_a_recorded_session_byte_for_byte() {
    let Ok(dir) = std::env::var("LOWLAT_CORPUS") else {
        eprintln!("skipping: set LOWLAT_CORPUS to a recording directory");
        return;
    };
    let dir = PathBuf::from(dir);
    let session = load_session(&dir);
    let envelope = Envelope::from_credential(&session.key, session.cipher)
        .expect("credential yields a key and a nonce prefix");

    let file = File::open(dir.join("wire.bin")).expect("wire.bin");
    let mut reader = BufReader::with_capacity(1 << 20, file);

    let mut header = [0u8; 16];
    reader.read_exact(&mut header).expect("file header");
    assert_eq!(&header[..8], MAGIC, "not a wire dump");

    let mut counts = Counts::default();
    let mut pending_wire: HashMap<u8, Vec<u8>> = HashMap::new();
    let mut pending_clear: HashMap<u8, Vec<u8>> = HashMap::new();
    let mut framing: HashMap<(u8, u8), Framing> = HashMap::new();
    // One ring per tracked channel per direction. Sized as the protocol
    // specifies rather than as the recording happens to need, so the real
    // window arithmetic is exercised.
    const TRACKED: usize = 3;
    const SLOT_LEN: usize = lowlat_core::MAX_CLEARTEXT - packet::HEADER_LEN;
    const SLOTS: usize = lowlat_core::channel::RING_SLOTS;
    let mut storages: Vec<(Vec<u8>, Vec<SlotMeta>)> = (0..TRACKED * 2)
        .map(|_| {
            (
                vec![0u8; SLOTS * SLOT_LEN],
                vec![SlotMeta::default(); SLOTS],
            )
        })
        .collect();
    let mut rings: Vec<RecvRing<'_>> = storages
        .iter_mut()
        .map(|(bodies, meta)| RecvRing::new(bodies, meta, SLOT_LEN).expect("ring storage"))
        .collect();
    let mut started = [false; TRACKED * 2];
    let mut message_buf = vec![0u8; 2 << 20];

    let mut scratch = vec![0u8; lowlat_core::MAX_DATAGRAM];
    let mut reencode = vec![0u8; lowlat_core::MAX_DATAGRAM];

    while let Some(record) = read_record(&mut reader) {
        match record.stage {
            STAGE_WIRE => {
                counts.wire += 1;
                let opened = envelope
                    .open(&record.data, &mut scratch)
                    .unwrap_or_else(|e| {
                        panic!("decrypt failed after {} records: {e}", counts.wire)
                    });
                pending_wire.insert(record.dir, opened.cleartext.to_vec());
            }
            STAGE_CLEARTEXT => {
                counts.cleartext += 1;
                pending_clear.insert(record.dir, record.data.clone());
            }
            other => panic!("unknown stage {other}"),
        }

        // Assertion 1: the decrypted bytes are the recorded cleartext.
        let (Some(wire), Some(clear)) = (
            pending_wire.get(&record.dir),
            pending_clear.get(&record.dir),
        ) else {
            continue;
        };
        assert_eq!(
            wire, clear,
            "decrypted cleartext differs from the recording, dir {}",
            record.dir
        );
        let cleartext = clear.clone();
        pending_wire.remove(&record.dir);
        pending_clear.remove(&record.dir);

        // Assertion 2: it parses.
        let parsed = packet::parse(&cleartext)
            .unwrap_or_else(|e| panic!("parse failed after {} packets: {e}", counts.cleartext));

        // Assertion 3: re-encoding reproduces the bytes.
        match &parsed {
            Packet::Data(data) => {
                counts.data += 1;
                let n = packet::encode_data(&mut reencode, data).expect("re-encode");
                assert_eq!(
                    &reencode[..n],
                    &cleartext[..],
                    "re-encoded data packet differs, ch {} seq {}",
                    data.channel,
                    data.seq
                );
            }
            Packet::Ack(ack) => {
                counts.acks += 1;
                let n = packet::encode_ack(&mut reencode, ack).expect("re-encode");
                assert_eq!(&reencode[..n], &cleartext[..], "re-encoded ack differs");
            }
        }

        // Assertion 4: message spans agree with the length prefix.
        let Packet::Data(data) = parsed else {
            continue;
        };
        let state = framing.entry((record.dir, data.channel)).or_default();
        match state.expected_seq {
            Some(expected) if data.seq == expected => {}
            Some(expected) if data.seq.wrapping_sub(expected) > u32::MAX / 2 => {
                // Already delivered: a retransmission, not a gap.
                counts.retransmits += 1;
                continue;
            }
            Some(_) => {
                // A gap. Drop the partial message and resynchronise.
                counts.resyncs += 1;
                *state = Framing::default();
            }
            None => {}
        }

        if state.remaining == 0 {
            let Ok(total) = message::parse_length_prefix(data.body) else {
                *state = Framing::default();
                continue;
            };
            state.declared = total as usize + message::LENGTH_PREFIX_LEN;
            state.remaining = message::fragment_count(total, session.body_capacity);
            state.collected = 0;
        }

        state.collected += data.body.len();
        state.remaining -= 1;
        state.expected_seq = Some(data.seq.wrapping_add(1));

        if state.remaining == 0 {
            assert!(
                data.last,
                "final fragment lacks the last flag, ch {} seq {}",
                data.channel, data.seq
            );
            assert_eq!(
                state.collected, state.declared,
                "collected bytes disagree with the declared length, ch {}",
                data.channel
            );
            counts.messages_validated += 1;
            state.collected = 0;
            state.declared = 0;
        } else {
            assert!(
                !data.last,
                "last flag set mid-message, ch {} seq {} with {} fragments left",
                data.channel, data.seq, state.remaining
            );
        }

        // Assertion 5: a real ring reassembles the same message.
        if (data.channel as usize) < TRACKED {
            let slot = record.dir as usize * TRACKED + data.channel as usize;
            let Some(ring) = rings.get_mut(slot) else {
                continue;
            };
            if !started[slot] {
                // The recording begins mid-stream for some channels; anchor the
                // ring where the channel actually starts.
                ring.reset_to(data.seq);
                started[slot] = true;
            }
            match ring.store(data.seq, data.body) {
                Stored::Accepted | Stored::Duplicate => {}
                other => panic!(
                    "ring refused ch {} seq {}: {other:?}",
                    data.channel, data.seq
                ),
            }
            while let Some(result) = ring.take_message(&mut message_buf) {
                let len = result.expect("reassembly");
                let content = message_buf.get(..len).expect("message fits");
                counts.reassembled += 1;
                match data.channel {
                    0 => {
                        let parsed = control::parse(content).expect("control message");
                        assert!(!control::op::name(parsed.opcode).is_empty());
                        counts.control_messages += 1;
                    }
                    1 => {
                        let header = video::parse(content).expect("video header");
                        assert!(
                            header.width > 0 && header.height > 0,
                            "implausible frame dimensions {}x{}",
                            header.width,
                            header.height
                        );

                        // **What we would emit for this frame, against what
                        // was recorded.** Parsing proves we can read a peer;
                        // this proves a peer could read us, which is the half
                        // that decides whether anything renders. A field we
                        // write at the wrong offset, in the wrong endianness,
                        // or with the rotation off by one lands here rather
                        // than in a client showing nothing.
                        let mut ours = [0u8; video::VIDEO_HEADER_LEN];
                        let written =
                            video::encode(&mut ours, &header).expect("re-encode the header");
                        assert_eq!(written, video::VIDEO_HEADER_LEN);
                        assert_eq!(
                            ours.as_slice(),
                            content
                                .get(..video::VIDEO_HEADER_LEN)
                                .expect("a header's worth"),
                            "our video header differs from the recorded one"
                        );

                        // The framing arithmetic a peer's reassembler runs.
                        // The recording fragmented this message at the same
                        // body capacity, so the counts have to agree.
                        let payload = content
                            .get(video::VIDEO_HEADER_LEN..)
                            .expect("a bitstream after the header");
                        let framed = message::Message::new(&ours, payload).expect("frame it");
                        assert_eq!(
                            framed.total_len() as usize,
                            content.len(),
                            "the length prefix would not cover this message"
                        );
                        assert_eq!(
                            framed.fragment_count(session.body_capacity),
                            message::fragment_count(
                                u32::try_from(content.len()).expect("message length"),
                                session.body_capacity
                            ),
                            "our fragmentation differs from the recording's"
                        );
                        counts.video_reemitted += 1;

                        if video::is_keyframe(content, video::Codec::H264) {
                            counts.keyframes += 1;
                        }
                        counts.video_messages += 1;
                    }
                    _ => {}
                }
            }
        }
    }

    eprintln!(
        "corpus: {} wire, {} cleartext, {} data, {} acks, {} messages validated, \
         {} retransmits, {} resyncs",
        counts.wire,
        counts.cleartext,
        counts.data,
        counts.acks,
        counts.messages_validated,
        counts.retransmits,
        counts.resyncs
    );
    eprintln!(
        "rings:  {} reassembled, {} control, {} video ({} re-emitted byte for byte), \
         {} keyframes",
        counts.reassembled,
        counts.control_messages,
        counts.video_messages,
        counts.video_reemitted,
        counts.keyframes
    );

    assert!(counts.wire > 1000, "corpus looks empty");
    assert!(
        counts.messages_validated > 1000,
        "too few complete messages validated: {}",
        counts.messages_validated
    );
    assert_eq!(
        counts.reassembled, counts.messages_validated,
        "the ring and the framing walk disagree on how many messages there were"
    );
    assert!(counts.video_messages > 100, "no video reassembled");
    assert_eq!(
        counts.video_reemitted, counts.video_messages,
        "a recorded video message was not re-emitted byte for byte"
    );
    assert!(counts.keyframes > 0, "no keyframe classified");
}

/// Phase 1 gate, widened: the received direction driven through a full
/// [`Session`] rather than bare rings.
///
/// The decisive assertion is the last one. The recorded peer is a real client,
/// and every acknowledgement it sent carries the contiguous frontier it had
/// reached on each channel. Feeding the same stream into our session must land
/// on exactly those numbers. Any divergence in reassembly anywhere across 112
/// seconds shows up here as a mismatch.
#[test]
fn a_full_session_replays_the_received_direction() {
    let Ok(dir) = std::env::var("LOWLAT_CORPUS") else {
        eprintln!("skipping: set LOWLAT_CORPUS to a recording directory");
        return;
    };
    let dir = PathBuf::from(dir);
    let recording = load_session(&dir);
    let envelope = Envelope::from_credential(&recording.key, recording.cipher).expect("credential");

    const TRACKED: u8 = 3;
    const SLOT_LEN: usize = lowlat_core::MAX_CLEARTEXT - packet::HEADER_LEN;
    const SLOTS: usize = lowlat_core::channel::RING_SLOTS;

    let mut storages: Vec<(Vec<u8>, Vec<SlotMeta>)> = (0..TRACKED)
        .map(|_| {
            (
                vec![0u8; SLOTS * SLOT_LEN],
                vec![SlotMeta::default(); SLOTS],
            )
        })
        .collect();

    let mut session = Session::new(envelope, lowlat_core::congestion::DEFAULT_LEVEL, 0.0);
    for (channel, (bodies, meta)) in storages.iter_mut().enumerate() {
        let channel = u8::try_from(channel).expect("channel index");
        session
            .attach_recv(
                channel,
                RecvRing::new(bodies, meta, SLOT_LEN).expect("ring storage"),
            )
            .expect("attach");
    }

    let file = File::open(dir.join("wire.bin")).expect("wire.bin");
    let mut reader = BufReader::with_capacity(1 << 20, file);
    let mut header = [0u8; 16];
    reader.read_exact(&mut header).expect("file header");

    let mut scratch = vec![0u8; lowlat_core::MAX_DATAGRAM];
    let mut message_buf = vec![0u8; 2 << 20];
    let mut peer_claim: Option<[u32; packet::CHANNEL_COUNT]> = None;
    let mut delivered = 0u64;
    let mut per_channel = [0u64; TRACKED as usize];
    let mut datagrams = 0u64;
    let mut inits_accepted = 0u64;

    while let Some(record) = read_record(&mut reader) {
        // The peer's own acknowledgements name the frontier it reached, and
        // the same direction carries its initialization.
        if record.dir == 1 && record.stage == STAGE_CLEARTEXT {
            match packet::parse(&record.data) {
                Ok(Packet::Ack(ack)) => peer_claim = Some(ack.cumulative),
                Ok(Packet::Data(data)) if data.channel == control::CONTROL_CHANNEL => {
                    // **The recorded initialization, parsed by the code that
                    // will meet a real one.** It arrives whole in one
                    // fragment, so nothing needs reassembling to reach it.
                    // A fixture we wrote would only prove the parser agrees
                    // with us; this is what a peer actually sent.
                    if let Some(content) = data.body.get(message::LENGTH_PREFIX_LEN..)
                        && let Ok(parsed) = control::parse(content)
                        && parsed.opcode == control::op::INIT
                    {
                        let asked = init::parse(parsed.body)
                            .expect("the recorded initialization was refused");
                        assert_eq!(asked.version, init::VERSION);
                        assert_eq!(
                            parsed.a0 as usize,
                            parsed.body.len(),
                            "argument 0 is not the body length"
                        );
                        assert!(
                            !asked.has_size_limit(),
                            "the no-limit sentinel was read as a limit"
                        );
                        assert!(
                            asked.flags & init::FLAG_BASE != 0,
                            "the base flag was absent from a real offer"
                        );
                        inits_accepted += 1;
                    }
                }
                _ => {}
            }
            continue;
        }
        if record.dir != 0 || record.stage != STAGE_WIRE {
            continue;
        }

        let now_ms = record.t_us as f64 / 1000.0;
        session
            .process_input(&record.data, now_ms, &mut scratch)
            .unwrap_or_else(|e| panic!("session refused a recorded datagram: {e}"));
        datagrams += 1;

        for channel in 0..TRACKED {
            while let Some(result) = session.take_message(channel, &mut message_buf) {
                let len = result.expect("reassembly");
                let content = message_buf.get(..len).expect("fits");
                match channel {
                    0 => {
                        control::parse(content).expect("control");
                    }
                    1 => {
                        let header = video::parse(content).expect("video");
                        assert!(header.width > 0 && header.height > 0);
                    }
                    _ => {}
                }
                delivered += 1;
                if let Some(slot) = per_channel.get_mut(channel as usize) {
                    *slot += 1;
                }
            }
        }
    }

    // The smoothed round trip stays zero here by construction: this replay has
    // no uplink, so no acknowledgement of ours is ever returned to sample.
    eprintln!(
        "session: {datagrams} datagrams in, {delivered} messages out {per_channel:?}, \
         {inits_accepted} initialisation accepted"
    );
    assert_eq!(
        inits_accepted, 1,
        "the recording's initialization was not found and parsed"
    );

    let claim = peer_claim.expect("the recording contained no peer acknowledgement");
    for channel in 0..TRACKED {
        let ours = session.recv_cumulative(channel).expect("ring attached");
        let theirs = *claim.get(channel as usize).expect("channel in range");
        assert_eq!(
            ours, theirs,
            "channel {channel}: our frontier {ours} differs from the peer's {theirs}"
        );
    }
    assert!(delivered > 1000, "too few messages delivered: {delivered}");
}
