/* automatically generated by rust-bindgen 0.72.1 */

// libvpl headers, third_party/vpl (see its PROVENANCE.md).

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    #[inline]
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val { byte | mask } else { byte & !mask }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    #[inline]
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
        }
    }
}
pub const MFX_IMPL_NAME_LEN: u32 = 32;
pub type mfxU8 = ::std::os::raw::c_uchar;
pub type mfxU16 = ::std::os::raw::c_ushort;
pub type mfxU32 = ::std::os::raw::c_uint;
pub type mfxI32 = ::std::os::raw::c_int;
pub type mfxU64 = ::std::os::raw::c_ulonglong;
pub type mfxI64 = ::std::os::raw::c_longlong;
pub type mfxHDL = *mut ::std::os::raw::c_void;
pub type mfxMemId = mfxHDL;
pub type mfxFP16 = ::std::os::raw::c_ushort;
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxStructVersion {
    pub __bindgen_anon_1: mfxStructVersion__bindgen_ty_1,
    pub Version: mfxU16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxStructVersion__bindgen_ty_1 {
    pub Minor: mfxU8,
    pub Major: mfxU8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxStructVersion__bindgen_ty_1"]
        [::std::mem::size_of::<mfxStructVersion__bindgen_ty_1>() - 2usize];
    ["Alignment of mfxStructVersion__bindgen_ty_1"]
        [::std::mem::align_of::<mfxStructVersion__bindgen_ty_1>() - 1usize];
    ["Offset of field: mfxStructVersion__bindgen_ty_1::Minor"]
        [::std::mem::offset_of!(mfxStructVersion__bindgen_ty_1, Minor) - 0usize];
    ["Offset of field: mfxStructVersion__bindgen_ty_1::Major"]
        [::std::mem::offset_of!(mfxStructVersion__bindgen_ty_1, Major) - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxStructVersion"][::std::mem::size_of::<mfxStructVersion>() - 2usize];
    ["Alignment of mfxStructVersion"][::std::mem::align_of::<mfxStructVersion>() - 2usize];
    ["Offset of field: mfxStructVersion::Version"]
        [::std::mem::offset_of!(mfxStructVersion, Version) - 0usize];
};
pub const MFX_ERR_NONE: mfxStatus = 0;
pub const MFX_ERR_UNKNOWN: mfxStatus = -1;
pub const MFX_ERR_NULL_PTR: mfxStatus = -2;
pub const MFX_ERR_UNSUPPORTED: mfxStatus = -3;
pub const MFX_ERR_MEMORY_ALLOC: mfxStatus = -4;
pub const MFX_ERR_NOT_ENOUGH_BUFFER: mfxStatus = -5;
pub const MFX_ERR_INVALID_HANDLE: mfxStatus = -6;
pub const MFX_ERR_LOCK_MEMORY: mfxStatus = -7;
pub const MFX_ERR_NOT_INITIALIZED: mfxStatus = -8;
pub const MFX_ERR_NOT_FOUND: mfxStatus = -9;
pub const MFX_ERR_MORE_DATA: mfxStatus = -10;
pub const MFX_ERR_MORE_SURFACE: mfxStatus = -11;
pub const MFX_ERR_ABORTED: mfxStatus = -12;
pub const MFX_ERR_DEVICE_LOST: mfxStatus = -13;
pub const MFX_ERR_INCOMPATIBLE_VIDEO_PARAM: mfxStatus = -14;
pub const MFX_ERR_INVALID_VIDEO_PARAM: mfxStatus = -15;
pub const MFX_ERR_UNDEFINED_BEHAVIOR: mfxStatus = -16;
pub const MFX_ERR_DEVICE_FAILED: mfxStatus = -17;
pub const MFX_ERR_MORE_BITSTREAM: mfxStatus = -18;
pub const MFX_ERR_GPU_HANG: mfxStatus = -21;
pub const MFX_ERR_REALLOC_SURFACE: mfxStatus = -22;
pub const MFX_ERR_RESOURCE_MAPPED: mfxStatus = -23;
pub const MFX_ERR_NOT_IMPLEMENTED: mfxStatus = -24;
pub const MFX_ERR_MORE_EXTBUFFER: mfxStatus = -25;
pub const MFX_WRN_IN_EXECUTION: mfxStatus = 1;
pub const MFX_WRN_DEVICE_BUSY: mfxStatus = 2;
pub const MFX_WRN_VIDEO_PARAM_CHANGED: mfxStatus = 3;
pub const MFX_WRN_PARTIAL_ACCELERATION: mfxStatus = 4;
pub const MFX_WRN_INCOMPATIBLE_VIDEO_PARAM: mfxStatus = 5;
pub const MFX_WRN_VALUE_NOT_CHANGED: mfxStatus = 6;
pub const MFX_WRN_OUT_OF_RANGE: mfxStatus = 7;
pub const MFX_WRN_FILTER_SKIPPED: mfxStatus = 10;
pub const MFX_ERR_NONE_PARTIAL_OUTPUT: mfxStatus = 12;
pub const MFX_WRN_ALLOC_TIMEOUT_EXPIRED: mfxStatus = 13;
pub const MFX_TASK_DONE: mfxStatus = 0;
pub const MFX_TASK_WORKING: mfxStatus = 8;
pub const MFX_TASK_BUSY: mfxStatus = 9;
pub const MFX_ERR_MORE_DATA_SUBMIT_TASK: mfxStatus = -10000;
pub type mfxStatus = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxGUID {
    pub Data: [mfxU8; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxGUID"][::std::mem::size_of::<mfxGUID>() - 16usize];
    ["Alignment of mfxGUID"][::std::mem::align_of::<mfxGUID>() - 1usize];
    ["Offset of field: mfxGUID::Data"][::std::mem::offset_of!(mfxGUID, Data) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxExtBuffer {
    pub BufferId: mfxU32,
    pub BufferSz: mfxU32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxExtBuffer"][::std::mem::size_of::<mfxExtBuffer>() - 8usize];
    ["Alignment of mfxExtBuffer"][::std::mem::align_of::<mfxExtBuffer>() - 4usize];
    ["Offset of field: mfxExtBuffer::BufferId"]
        [::std::mem::offset_of!(mfxExtBuffer, BufferId) - 0usize];
    ["Offset of field: mfxExtBuffer::BufferSz"]
        [::std::mem::offset_of!(mfxExtBuffer, BufferSz) - 4usize];
};
pub type mfxIMPL = mfxI32;
pub const MFX_IMPL_AUTO: _bindgen_ty_1 = 0;
pub const MFX_IMPL_SOFTWARE: _bindgen_ty_1 = 1;
pub const MFX_IMPL_HARDWARE: _bindgen_ty_1 = 2;
pub const MFX_IMPL_AUTO_ANY: _bindgen_ty_1 = 3;
pub const MFX_IMPL_HARDWARE_ANY: _bindgen_ty_1 = 4;
pub const MFX_IMPL_HARDWARE2: _bindgen_ty_1 = 5;
pub const MFX_IMPL_HARDWARE3: _bindgen_ty_1 = 6;
pub const MFX_IMPL_HARDWARE4: _bindgen_ty_1 = 7;
pub const MFX_IMPL_RUNTIME: _bindgen_ty_1 = 8;
pub const MFX_IMPL_VIA_ANY: _bindgen_ty_1 = 256;
pub const MFX_IMPL_VIA_D3D9: _bindgen_ty_1 = 512;
pub const MFX_IMPL_VIA_D3D11: _bindgen_ty_1 = 768;
pub const MFX_IMPL_VIA_VAAPI: _bindgen_ty_1 = 1024;
pub const MFX_IMPL_VIA_HDDLUNITE: _bindgen_ty_1 = 1280;
pub const MFX_IMPL_UNSUPPORTED: _bindgen_ty_1 = 0;
pub type _bindgen_ty_1 = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxVersion {
    pub __bindgen_anon_1: mfxVersion__bindgen_ty_1,
    pub Version: mfxU32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxVersion__bindgen_ty_1 {
    pub Minor: mfxU16,
    pub Major: mfxU16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxVersion__bindgen_ty_1"]
        [::std::mem::size_of::<mfxVersion__bindgen_ty_1>() - 4usize];
    ["Alignment of mfxVersion__bindgen_ty_1"]
        [::std::mem::align_of::<mfxVersion__bindgen_ty_1>() - 2usize];
    ["Offset of field: mfxVersion__bindgen_ty_1::Minor"]
        [::std::mem::offset_of!(mfxVersion__bindgen_ty_1, Minor) - 0usize];
    ["Offset of field: mfxVersion__bindgen_ty_1::Major"]
        [::std::mem::offset_of!(mfxVersion__bindgen_ty_1, Major) - 2usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxVersion"][::std::mem::size_of::<mfxVersion>() - 4usize];
    ["Alignment of mfxVersion"][::std::mem::align_of::<mfxVersion>() - 4usize];
    ["Offset of field: mfxVersion::Version"][::std::mem::offset_of!(mfxVersion, Version) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _mfxEncryptedData {
    _unused: [u8; 0],
}
pub type mfxEncryptedData = _mfxEncryptedData;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxBitstream {
    pub __bindgen_anon_1: mfxBitstream__bindgen_ty_1,
    pub DecodeTimeStamp: mfxI64,
    pub TimeStamp: mfxU64,
    pub Data: *mut mfxU8,
    pub DataOffset: mfxU32,
    pub DataLength: mfxU32,
    pub MaxLength: mfxU32,
    pub PicStruct: mfxU16,
    pub FrameType: mfxU16,
    pub DataFlag: mfxU16,
    pub reserved2: mfxU16,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxBitstream__bindgen_ty_1 {
    pub __bindgen_anon_1: mfxBitstream__bindgen_ty_1__bindgen_ty_1,
    pub reserved: [mfxU32; 6usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxBitstream__bindgen_ty_1__bindgen_ty_1 {
    pub EncryptedData: *mut mfxEncryptedData,
    pub ExtParam: *mut *mut mfxExtBuffer,
    pub NumExtParam: mfxU16,
    pub reserved1: mfxU16,
    pub CodecId: mfxU32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxBitstream__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<mfxBitstream__bindgen_ty_1__bindgen_ty_1>() - 24usize];
    ["Alignment of mfxBitstream__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<mfxBitstream__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: mfxBitstream__bindgen_ty_1__bindgen_ty_1::EncryptedData"]
        [::std::mem::offset_of!(mfxBitstream__bindgen_ty_1__bindgen_ty_1, EncryptedData) - 0usize];
    ["Offset of field: mfxBitstream__bindgen_ty_1__bindgen_ty_1::ExtParam"]
        [::std::mem::offset_of!(mfxBitstream__bindgen_ty_1__bindgen_ty_1, ExtParam) - 8usize];
    ["Offset of field: mfxBitstream__bindgen_ty_1__bindgen_ty_1::NumExtParam"]
        [::std::mem::offset_of!(mfxBitstream__bindgen_ty_1__bindgen_ty_1, NumExtParam) - 16usize];
    ["Offset of field: mfxBitstream__bindgen_ty_1__bindgen_ty_1::reserved1"]
        [::std::mem::offset_of!(mfxBitstream__bindgen_ty_1__bindgen_ty_1, reserved1) - 18usize];
    ["Offset of field: mfxBitstream__bindgen_ty_1__bindgen_ty_1::CodecId"]
        [::std::mem::offset_of!(mfxBitstream__bindgen_ty_1__bindgen_ty_1, CodecId) - 20usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxBitstream__bindgen_ty_1"]
        [::std::mem::size_of::<mfxBitstream__bindgen_ty_1>() - 24usize];
    ["Alignment of mfxBitstream__bindgen_ty_1"]
        [::std::mem::align_of::<mfxBitstream__bindgen_ty_1>() - 8usize];
    ["Offset of field: mfxBitstream__bindgen_ty_1::reserved"]
        [::std::mem::offset_of!(mfxBitstream__bindgen_ty_1, reserved) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxBitstream"][::std::mem::size_of::<mfxBitstream>() - 72usize];
    ["Alignment of mfxBitstream"][::std::mem::align_of::<mfxBitstream>() - 8usize];
    ["Offset of field: mfxBitstream::DecodeTimeStamp"]
        [::std::mem::offset_of!(mfxBitstream, DecodeTimeStamp) - 24usize];
    ["Offset of field: mfxBitstream::TimeStamp"]
        [::std::mem::offset_of!(mfxBitstream, TimeStamp) - 32usize];
    ["Offset of field: mfxBitstream::Data"][::std::mem::offset_of!(mfxBitstream, Data) - 40usize];
    ["Offset of field: mfxBitstream::DataOffset"]
        [::std::mem::offset_of!(mfxBitstream, DataOffset) - 48usize];
    ["Offset of field: mfxBitstream::DataLength"]
        [::std::mem::offset_of!(mfxBitstream, DataLength) - 52usize];
    ["Offset of field: mfxBitstream::MaxLength"]
        [::std::mem::offset_of!(mfxBitstream, MaxLength) - 56usize];
    ["Offset of field: mfxBitstream::PicStruct"]
        [::std::mem::offset_of!(mfxBitstream, PicStruct) - 60usize];
    ["Offset of field: mfxBitstream::FrameType"]
        [::std::mem::offset_of!(mfxBitstream, FrameType) - 62usize];
    ["Offset of field: mfxBitstream::DataFlag"]
        [::std::mem::offset_of!(mfxBitstream, DataFlag) - 64usize];
    ["Offset of field: mfxBitstream::reserved2"]
        [::std::mem::offset_of!(mfxBitstream, reserved2) - 66usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _mfxSyncPoint {
    _unused: [u8; 0],
}
pub type mfxSyncPoint = *mut _mfxSyncPoint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxInitParam {
    pub Implementation: mfxIMPL,
    pub Version: mfxVersion,
    pub ExternalThreads: mfxU16,
    pub __bindgen_anon_1: mfxInitParam__bindgen_ty_1,
    pub GPUCopy: mfxU16,
    pub reserved: [mfxU16; 21usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxInitParam__bindgen_ty_1 {
    pub __bindgen_anon_1: mfxInitParam__bindgen_ty_1__bindgen_ty_1,
    pub reserved2: [mfxU16; 5usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxInitParam__bindgen_ty_1__bindgen_ty_1 {
    pub ExtParam: *mut *mut mfxExtBuffer,
    pub NumExtParam: mfxU16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInitParam__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<mfxInitParam__bindgen_ty_1__bindgen_ty_1>() - 16usize];
    ["Alignment of mfxInitParam__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<mfxInitParam__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: mfxInitParam__bindgen_ty_1__bindgen_ty_1::ExtParam"]
        [::std::mem::offset_of!(mfxInitParam__bindgen_ty_1__bindgen_ty_1, ExtParam) - 0usize];
    ["Offset of field: mfxInitParam__bindgen_ty_1__bindgen_ty_1::NumExtParam"]
        [::std::mem::offset_of!(mfxInitParam__bindgen_ty_1__bindgen_ty_1, NumExtParam) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInitParam__bindgen_ty_1"]
        [::std::mem::size_of::<mfxInitParam__bindgen_ty_1>() - 16usize];
    ["Alignment of mfxInitParam__bindgen_ty_1"]
        [::std::mem::align_of::<mfxInitParam__bindgen_ty_1>() - 8usize];
    ["Offset of field: mfxInitParam__bindgen_ty_1::reserved2"]
        [::std::mem::offset_of!(mfxInitParam__bindgen_ty_1, reserved2) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInitParam"][::std::mem::size_of::<mfxInitParam>() - 80usize];
    ["Alignment of mfxInitParam"][::std::mem::align_of::<mfxInitParam>() - 8usize];
    ["Offset of field: mfxInitParam::Implementation"]
        [::std::mem::offset_of!(mfxInitParam, Implementation) - 0usize];
    ["Offset of field: mfxInitParam::Version"]
        [::std::mem::offset_of!(mfxInitParam, Version) - 4usize];
    ["Offset of field: mfxInitParam::ExternalThreads"]
        [::std::mem::offset_of!(mfxInitParam, ExternalThreads) - 8usize];
    ["Offset of field: mfxInitParam::GPUCopy"]
        [::std::mem::offset_of!(mfxInitParam, GPUCopy) - 32usize];
    ["Offset of field: mfxInitParam::reserved"]
        [::std::mem::offset_of!(mfxInitParam, reserved) - 34usize];
};
pub const MFX_EXTBUFF_THREADS_PARAM: _bindgen_ty_3 = 1346652244;
pub type _bindgen_ty_3 = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxExtThreadsParam {
    pub Header: mfxExtBuffer,
    pub NumThread: mfxU16,
    pub SchedulingType: mfxI32,
    pub Priority: mfxI32,
    pub reserved: [mfxU16; 55usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxExtThreadsParam"][::std::mem::size_of::<mfxExtThreadsParam>() - 132usize];
    ["Alignment of mfxExtThreadsParam"][::std::mem::align_of::<mfxExtThreadsParam>() - 4usize];
    ["Offset of field: mfxExtThreadsParam::Header"]
        [::std::mem::offset_of!(mfxExtThreadsParam, Header) - 0usize];
    ["Offset of field: mfxExtThreadsParam::NumThread"]
        [::std::mem::offset_of!(mfxExtThreadsParam, NumThread) - 8usize];
    ["Offset of field: mfxExtThreadsParam::SchedulingType"]
        [::std::mem::offset_of!(mfxExtThreadsParam, SchedulingType) - 12usize];
    ["Offset of field: mfxExtThreadsParam::Priority"]
        [::std::mem::offset_of!(mfxExtThreadsParam, Priority) - 16usize];
    ["Offset of field: mfxExtThreadsParam::reserved"]
        [::std::mem::offset_of!(mfxExtThreadsParam, reserved) - 20usize];
};
pub const MFX_RESOURCE_SYSTEM_SURFACE: mfxResourceType = 1;
pub const MFX_RESOURCE_VA_SURFACE_PTR: mfxResourceType = 2;
pub const MFX_RESOURCE_VA_SURFACE: mfxResourceType = 2;
pub const MFX_RESOURCE_VA_BUFFER_PTR: mfxResourceType = 3;
pub const MFX_RESOURCE_VA_BUFFER: mfxResourceType = 3;
pub const MFX_RESOURCE_DX9_SURFACE: mfxResourceType = 4;
pub const MFX_RESOURCE_DX11_TEXTURE: mfxResourceType = 5;
pub const MFX_RESOURCE_DX12_RESOURCE: mfxResourceType = 6;
pub const MFX_RESOURCE_DMA_RESOURCE: mfxResourceType = 7;
pub const MFX_RESOURCE_HDDLUNITE_REMOTE_MEMORY: mfxResourceType = 8;
pub type mfxResourceType = ::std::os::raw::c_int;
pub const MFX_ACCEL_MODE_NA: mfxAccelerationMode = 0;
pub const MFX_ACCEL_MODE_VIA_D3D9: mfxAccelerationMode = 512;
pub const MFX_ACCEL_MODE_VIA_D3D11: mfxAccelerationMode = 768;
pub const MFX_ACCEL_MODE_VIA_VAAPI: mfxAccelerationMode = 1024;
pub const MFX_ACCEL_MODE_VIA_VAAPI_DRM_RENDER_NODE: mfxAccelerationMode = 1024;
pub const MFX_ACCEL_MODE_VIA_VAAPI_DRM_MODESET: mfxAccelerationMode = 1025;
pub const MFX_ACCEL_MODE_VIA_VAAPI_GLX: mfxAccelerationMode = 1026;
pub const MFX_ACCEL_MODE_VIA_VAAPI_X11: mfxAccelerationMode = 1027;
pub const MFX_ACCEL_MODE_VIA_VAAPI_WAYLAND: mfxAccelerationMode = 1028;
pub const MFX_ACCEL_MODE_VIA_HDDLUNITE: mfxAccelerationMode = 1280;
pub type mfxAccelerationMode = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxInitializationParam {
    pub AccelerationMode: mfxAccelerationMode,
    pub reserved: [mfxU16; 3usize],
    pub NumExtParam: mfxU16,
    pub ExtParam: *mut *mut mfxExtBuffer,
    pub VendorImplID: mfxU32,
    pub reserved2: [mfxU32; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInitializationParam"][::std::mem::size_of::<mfxInitializationParam>() - 40usize];
    ["Alignment of mfxInitializationParam"]
        [::std::mem::align_of::<mfxInitializationParam>() - 8usize];
    ["Offset of field: mfxInitializationParam::AccelerationMode"]
        [::std::mem::offset_of!(mfxInitializationParam, AccelerationMode) - 0usize];
    ["Offset of field: mfxInitializationParam::reserved"]
        [::std::mem::offset_of!(mfxInitializationParam, reserved) - 4usize];
    ["Offset of field: mfxInitializationParam::NumExtParam"]
        [::std::mem::offset_of!(mfxInitializationParam, NumExtParam) - 10usize];
    ["Offset of field: mfxInitializationParam::ExtParam"]
        [::std::mem::offset_of!(mfxInitializationParam, ExtParam) - 16usize];
    ["Offset of field: mfxInitializationParam::VendorImplID"]
        [::std::mem::offset_of!(mfxInitializationParam, VendorImplID) - 24usize];
    ["Offset of field: mfxInitializationParam::reserved2"]
        [::std::mem::offset_of!(mfxInitializationParam, reserved2) - 28usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _mfxSession {
    _unused: [u8; 0],
}
pub type mfxSession = *mut _mfxSession;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxFrameId {
    pub TemporalId: mfxU16,
    pub PriorityId: mfxU16,
    pub __bindgen_anon_1: mfxFrameId__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxFrameId__bindgen_ty_1 {
    pub __bindgen_anon_1: mfxFrameId__bindgen_ty_1__bindgen_ty_1,
    pub __bindgen_anon_2: mfxFrameId__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxFrameId__bindgen_ty_1__bindgen_ty_1 {
    pub DependencyId: mfxU16,
    pub QualityId: mfxU16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameId__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<mfxFrameId__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Alignment of mfxFrameId__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<mfxFrameId__bindgen_ty_1__bindgen_ty_1>() - 2usize];
    ["Offset of field: mfxFrameId__bindgen_ty_1__bindgen_ty_1::DependencyId"]
        [::std::mem::offset_of!(mfxFrameId__bindgen_ty_1__bindgen_ty_1, DependencyId) - 0usize];
    ["Offset of field: mfxFrameId__bindgen_ty_1__bindgen_ty_1::QualityId"]
        [::std::mem::offset_of!(mfxFrameId__bindgen_ty_1__bindgen_ty_1, QualityId) - 2usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxFrameId__bindgen_ty_1__bindgen_ty_2 {
    pub ViewId: mfxU16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameId__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<mfxFrameId__bindgen_ty_1__bindgen_ty_2>() - 2usize];
    ["Alignment of mfxFrameId__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<mfxFrameId__bindgen_ty_1__bindgen_ty_2>() - 2usize];
    ["Offset of field: mfxFrameId__bindgen_ty_1__bindgen_ty_2::ViewId"]
        [::std::mem::offset_of!(mfxFrameId__bindgen_ty_1__bindgen_ty_2, ViewId) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameId__bindgen_ty_1"]
        [::std::mem::size_of::<mfxFrameId__bindgen_ty_1>() - 4usize];
    ["Alignment of mfxFrameId__bindgen_ty_1"]
        [::std::mem::align_of::<mfxFrameId__bindgen_ty_1>() - 2usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameId"][::std::mem::size_of::<mfxFrameId>() - 8usize];
    ["Alignment of mfxFrameId"][::std::mem::align_of::<mfxFrameId>() - 2usize];
    ["Offset of field: mfxFrameId::TemporalId"]
        [::std::mem::offset_of!(mfxFrameId, TemporalId) - 0usize];
    ["Offset of field: mfxFrameId::PriorityId"]
        [::std::mem::offset_of!(mfxFrameId, PriorityId) - 2usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxFrameInfo {
    pub reserved: [mfxU32; 4usize],
    pub ChannelId: mfxU16,
    pub BitDepthLuma: mfxU16,
    pub BitDepthChroma: mfxU16,
    pub Shift: mfxU16,
    pub FrameId: mfxFrameId,
    pub FourCC: mfxU32,
    pub __bindgen_anon_1: mfxFrameInfo__bindgen_ty_1,
    pub FrameRateExtN: mfxU32,
    pub FrameRateExtD: mfxU32,
    pub reserved3: mfxU16,
    pub AspectRatioW: mfxU16,
    pub AspectRatioH: mfxU16,
    pub PicStruct: mfxU16,
    pub ChromaFormat: mfxU16,
    pub reserved2: mfxU16,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxFrameInfo__bindgen_ty_1 {
    pub __bindgen_anon_1: mfxFrameInfo__bindgen_ty_1__bindgen_ty_1,
    pub __bindgen_anon_2: mfxFrameInfo__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxFrameInfo__bindgen_ty_1__bindgen_ty_1 {
    pub Width: mfxU16,
    pub Height: mfxU16,
    pub CropX: mfxU16,
    pub CropY: mfxU16,
    pub CropW: mfxU16,
    pub CropH: mfxU16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameInfo__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<mfxFrameInfo__bindgen_ty_1__bindgen_ty_1>() - 12usize];
    ["Alignment of mfxFrameInfo__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<mfxFrameInfo__bindgen_ty_1__bindgen_ty_1>() - 2usize];
    ["Offset of field: mfxFrameInfo__bindgen_ty_1__bindgen_ty_1::Width"]
        [::std::mem::offset_of!(mfxFrameInfo__bindgen_ty_1__bindgen_ty_1, Width) - 0usize];
    ["Offset of field: mfxFrameInfo__bindgen_ty_1__bindgen_ty_1::Height"]
        [::std::mem::offset_of!(mfxFrameInfo__bindgen_ty_1__bindgen_ty_1, Height) - 2usize];
    ["Offset of field: mfxFrameInfo__bindgen_ty_1__bindgen_ty_1::CropX"]
        [::std::mem::offset_of!(mfxFrameInfo__bindgen_ty_1__bindgen_ty_1, CropX) - 4usize];
    ["Offset of field: mfxFrameInfo__bindgen_ty_1__bindgen_ty_1::CropY"]
        [::std::mem::offset_of!(mfxFrameInfo__bindgen_ty_1__bindgen_ty_1, CropY) - 6usize];
    ["Offset of field: mfxFrameInfo__bindgen_ty_1__bindgen_ty_1::CropW"]
        [::std::mem::offset_of!(mfxFrameInfo__bindgen_ty_1__bindgen_ty_1, CropW) - 8usize];
    ["Offset of field: mfxFrameInfo__bindgen_ty_1__bindgen_ty_1::CropH"]
        [::std::mem::offset_of!(mfxFrameInfo__bindgen_ty_1__bindgen_ty_1, CropH) - 10usize];
};
#[repr(C, packed(4))]
#[derive(Debug, Copy, Clone)]
pub struct mfxFrameInfo__bindgen_ty_1__bindgen_ty_2 {
    pub BufferSize: mfxU64,
    pub reserved5: mfxU32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameInfo__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<mfxFrameInfo__bindgen_ty_1__bindgen_ty_2>() - 12usize];
    ["Alignment of mfxFrameInfo__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<mfxFrameInfo__bindgen_ty_1__bindgen_ty_2>() - 4usize];
    ["Offset of field: mfxFrameInfo__bindgen_ty_1__bindgen_ty_2::BufferSize"]
        [::std::mem::offset_of!(mfxFrameInfo__bindgen_ty_1__bindgen_ty_2, BufferSize) - 0usize];
    ["Offset of field: mfxFrameInfo__bindgen_ty_1__bindgen_ty_2::reserved5"]
        [::std::mem::offset_of!(mfxFrameInfo__bindgen_ty_1__bindgen_ty_2, reserved5) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameInfo__bindgen_ty_1"]
        [::std::mem::size_of::<mfxFrameInfo__bindgen_ty_1>() - 12usize];
    ["Alignment of mfxFrameInfo__bindgen_ty_1"]
        [::std::mem::align_of::<mfxFrameInfo__bindgen_ty_1>() - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameInfo"][::std::mem::size_of::<mfxFrameInfo>() - 68usize];
    ["Alignment of mfxFrameInfo"][::std::mem::align_of::<mfxFrameInfo>() - 4usize];
    ["Offset of field: mfxFrameInfo::reserved"]
        [::std::mem::offset_of!(mfxFrameInfo, reserved) - 0usize];
    ["Offset of field: mfxFrameInfo::ChannelId"]
        [::std::mem::offset_of!(mfxFrameInfo, ChannelId) - 16usize];
    ["Offset of field: mfxFrameInfo::BitDepthLuma"]
        [::std::mem::offset_of!(mfxFrameInfo, BitDepthLuma) - 18usize];
    ["Offset of field: mfxFrameInfo::BitDepthChroma"]
        [::std::mem::offset_of!(mfxFrameInfo, BitDepthChroma) - 20usize];
    ["Offset of field: mfxFrameInfo::Shift"][::std::mem::offset_of!(mfxFrameInfo, Shift) - 22usize];
    ["Offset of field: mfxFrameInfo::FrameId"]
        [::std::mem::offset_of!(mfxFrameInfo, FrameId) - 24usize];
    ["Offset of field: mfxFrameInfo::FourCC"]
        [::std::mem::offset_of!(mfxFrameInfo, FourCC) - 32usize];
    ["Offset of field: mfxFrameInfo::FrameRateExtN"]
        [::std::mem::offset_of!(mfxFrameInfo, FrameRateExtN) - 48usize];
    ["Offset of field: mfxFrameInfo::FrameRateExtD"]
        [::std::mem::offset_of!(mfxFrameInfo, FrameRateExtD) - 52usize];
    ["Offset of field: mfxFrameInfo::reserved3"]
        [::std::mem::offset_of!(mfxFrameInfo, reserved3) - 56usize];
    ["Offset of field: mfxFrameInfo::AspectRatioW"]
        [::std::mem::offset_of!(mfxFrameInfo, AspectRatioW) - 58usize];
    ["Offset of field: mfxFrameInfo::AspectRatioH"]
        [::std::mem::offset_of!(mfxFrameInfo, AspectRatioH) - 60usize];
    ["Offset of field: mfxFrameInfo::PicStruct"]
        [::std::mem::offset_of!(mfxFrameInfo, PicStruct) - 62usize];
    ["Offset of field: mfxFrameInfo::ChromaFormat"]
        [::std::mem::offset_of!(mfxFrameInfo, ChromaFormat) - 64usize];
    ["Offset of field: mfxFrameInfo::reserved2"]
        [::std::mem::offset_of!(mfxFrameInfo, reserved2) - 66usize];
};
pub const MFX_FOURCC_NV12: _bindgen_ty_5 = 842094158;
pub const MFX_FOURCC_YV12: _bindgen_ty_5 = 842094169;
pub const MFX_FOURCC_NV16: _bindgen_ty_5 = 909203022;
pub const MFX_FOURCC_YUY2: _bindgen_ty_5 = 844715353;
pub const MFX_FOURCC_RGB565: _bindgen_ty_5 = 843204434;
pub const MFX_FOURCC_RGBP: _bindgen_ty_5 = 1346520914;
pub const MFX_FOURCC_RGB3: _bindgen_ty_5 = 859981650;
pub const MFX_FOURCC_RGB4: _bindgen_ty_5 = 876758866;
pub const MFX_FOURCC_P8: _bindgen_ty_5 = 41;
pub const MFX_FOURCC_P8_TEXTURE: _bindgen_ty_5 = 1112356944;
pub const MFX_FOURCC_P010: _bindgen_ty_5 = 808530000;
pub const MFX_FOURCC_P016: _bindgen_ty_5 = 909193296;
pub const MFX_FOURCC_P210: _bindgen_ty_5 = 808530512;
pub const MFX_FOURCC_BGR4: _bindgen_ty_5 = 877807426;
pub const MFX_FOURCC_A2RGB10: _bindgen_ty_5 = 808535890;
pub const MFX_FOURCC_ARGB16: _bindgen_ty_5 = 909199186;
pub const MFX_FOURCC_ABGR16: _bindgen_ty_5 = 909199170;
pub const MFX_FOURCC_R16: _bindgen_ty_5 = 1429614930;
pub const MFX_FOURCC_AYUV: _bindgen_ty_5 = 1448433985;
pub const MFX_FOURCC_AYUV_RGB4: _bindgen_ty_5 = 1498764865;
pub const MFX_FOURCC_UYVY: _bindgen_ty_5 = 1498831189;
pub const MFX_FOURCC_Y210: _bindgen_ty_5 = 808530521;
pub const MFX_FOURCC_Y410: _bindgen_ty_5 = 808531033;
pub const MFX_FOURCC_Y216: _bindgen_ty_5 = 909193817;
pub const MFX_FOURCC_Y416: _bindgen_ty_5 = 909194329;
pub const MFX_FOURCC_NV21: _bindgen_ty_5 = 825382478;
pub const MFX_FOURCC_IYUV: _bindgen_ty_5 = 1448433993;
pub const MFX_FOURCC_I010: _bindgen_ty_5 = 808529993;
pub const MFX_FOURCC_I210: _bindgen_ty_5 = 808530505;
pub const MFX_FOURCC_I420: _bindgen_ty_5 = 1448433993;
pub const MFX_FOURCC_I422: _bindgen_ty_5 = 842150985;
pub const MFX_FOURCC_BGRA: _bindgen_ty_5 = 876758866;
pub const MFX_FOURCC_BGRP: _bindgen_ty_5 = 1347569474;
pub const MFX_FOURCC_XYUV: _bindgen_ty_5 = 1448434008;
pub const MFX_FOURCC_ABGR16F: _bindgen_ty_5 = 1179797314;
pub type _bindgen_ty_5 = ::std::os::raw::c_int;
pub const MFX_PICSTRUCT_UNKNOWN: _bindgen_ty_6 = 0;
pub const MFX_PICSTRUCT_PROGRESSIVE: _bindgen_ty_6 = 1;
pub const MFX_PICSTRUCT_FIELD_TFF: _bindgen_ty_6 = 2;
pub const MFX_PICSTRUCT_FIELD_BFF: _bindgen_ty_6 = 4;
pub const MFX_PICSTRUCT_FIELD_REPEATED: _bindgen_ty_6 = 16;
pub const MFX_PICSTRUCT_FRAME_DOUBLING: _bindgen_ty_6 = 32;
pub const MFX_PICSTRUCT_FRAME_TRIPLING: _bindgen_ty_6 = 64;
pub const MFX_PICSTRUCT_FIELD_SINGLE: _bindgen_ty_6 = 256;
pub const MFX_PICSTRUCT_FIELD_TOP: _bindgen_ty_6 = 258;
pub const MFX_PICSTRUCT_FIELD_BOTTOM: _bindgen_ty_6 = 260;
pub const MFX_PICSTRUCT_FIELD_PAIRED_PREV: _bindgen_ty_6 = 512;
pub const MFX_PICSTRUCT_FIELD_PAIRED_NEXT: _bindgen_ty_6 = 1024;
pub type _bindgen_ty_6 = ::std::os::raw::c_int;
pub const MFX_CHROMAFORMAT_MONOCHROME: _bindgen_ty_7 = 0;
pub const MFX_CHROMAFORMAT_YUV420: _bindgen_ty_7 = 1;
pub const MFX_CHROMAFORMAT_YUV422: _bindgen_ty_7 = 2;
pub const MFX_CHROMAFORMAT_YUV444: _bindgen_ty_7 = 3;
pub const MFX_CHROMAFORMAT_YUV400: _bindgen_ty_7 = 0;
pub const MFX_CHROMAFORMAT_YUV411: _bindgen_ty_7 = 4;
pub const MFX_CHROMAFORMAT_YUV422H: _bindgen_ty_7 = 2;
pub const MFX_CHROMAFORMAT_YUV422V: _bindgen_ty_7 = 5;
pub const MFX_CHROMAFORMAT_RESERVED1: _bindgen_ty_7 = 6;
pub type _bindgen_ty_7 = ::std::os::raw::c_int;
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Copy, Clone)]
pub struct mfxY410 {
    pub _bitfield_align_1: [u16; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxY410"][::std::mem::size_of::<mfxY410>() - 4usize];
    ["Alignment of mfxY410"][::std::mem::align_of::<mfxY410>() - 4usize];
};
impl mfxY410 {
    #[inline]
    pub fn U(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 10u8) as u32) }
    }
    #[inline]
    pub fn set_U(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 10u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn U_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                10u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_U_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                10u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn Y(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(10usize, 10u8) as u32) }
    }
    #[inline]
    pub fn set_Y(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(10usize, 10u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn Y_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                10usize,
                10u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_Y_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                10usize,
                10u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn V(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(20usize, 10u8) as u32) }
    }
    #[inline]
    pub fn set_V(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(20usize, 10u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn V_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                20usize,
                10u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_V_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                20usize,
                10u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn A(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(30usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_A(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(30usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn A_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                30usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_A_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                30usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        U: mfxU32,
        Y: mfxU32,
        V: mfxU32,
        A: mfxU32,
    ) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 10u8, {
            let U: u32 = unsafe { ::std::mem::transmute(U) };
            U as u64
        });
        __bindgen_bitfield_unit.set(10usize, 10u8, {
            let Y: u32 = unsafe { ::std::mem::transmute(Y) };
            Y as u64
        });
        __bindgen_bitfield_unit.set(20usize, 10u8, {
            let V: u32 = unsafe { ::std::mem::transmute(V) };
            V as u64
        });
        __bindgen_bitfield_unit.set(30usize, 2u8, {
            let A: u32 = unsafe { ::std::mem::transmute(A) };
            A as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Copy, Clone)]
pub struct mfxY416 {
    pub _bitfield_align_1: [u16; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 8usize]>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxY416"][::std::mem::size_of::<mfxY416>() - 8usize];
    ["Alignment of mfxY416"][::std::mem::align_of::<mfxY416>() - 4usize];
};
impl mfxY416 {
    #[inline]
    pub fn U(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 16u8) as u32) }
    }
    #[inline]
    pub fn set_U(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 16u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn U_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                16u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_U_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                16u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn Y(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(16usize, 16u8) as u32) }
    }
    #[inline]
    pub fn set_Y(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(16usize, 16u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn Y_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                16usize,
                16u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_Y_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                16usize,
                16u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn V(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(32usize, 16u8) as u32) }
    }
    #[inline]
    pub fn set_V(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(32usize, 16u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn V_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                32usize,
                16u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_V_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                32usize,
                16u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn A(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(48usize, 16u8) as u32) }
    }
    #[inline]
    pub fn set_A(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(48usize, 16u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn A_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 8usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                48usize,
                16u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_A_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 8usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                48usize,
                16u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        U: mfxU32,
        Y: mfxU32,
        V: mfxU32,
        A: mfxU32,
    ) -> __BindgenBitfieldUnit<[u8; 8usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 8usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 16u8, {
            let U: u32 = unsafe { ::std::mem::transmute(U) };
            U as u64
        });
        __bindgen_bitfield_unit.set(16usize, 16u8, {
            let Y: u32 = unsafe { ::std::mem::transmute(Y) };
            Y as u64
        });
        __bindgen_bitfield_unit.set(32usize, 16u8, {
            let V: u32 = unsafe { ::std::mem::transmute(V) };
            V as u64
        });
        __bindgen_bitfield_unit.set(48usize, 16u8, {
            let A: u32 = unsafe { ::std::mem::transmute(A) };
            A as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Copy, Clone)]
pub struct mfxA2RGB10 {
    pub _bitfield_align_1: [u16; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxA2RGB10"][::std::mem::size_of::<mfxA2RGB10>() - 4usize];
    ["Alignment of mfxA2RGB10"][::std::mem::align_of::<mfxA2RGB10>() - 4usize];
};
impl mfxA2RGB10 {
    #[inline]
    pub fn B(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 10u8) as u32) }
    }
    #[inline]
    pub fn set_B(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 10u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn B_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                10u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_B_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                10u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn G(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(10usize, 10u8) as u32) }
    }
    #[inline]
    pub fn set_G(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(10usize, 10u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn G_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                10usize,
                10u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_G_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                10usize,
                10u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn R(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(20usize, 10u8) as u32) }
    }
    #[inline]
    pub fn set_R(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(20usize, 10u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn R_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                20usize,
                10u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_R_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                20usize,
                10u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn A(&self) -> mfxU32 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(30usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_A(&mut self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(30usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn A_raw(this: *const Self) -> mfxU32 {
        unsafe {
            ::std::mem::transmute(<__BindgenBitfieldUnit<[u8; 4usize]>>::raw_get(
                ::std::ptr::addr_of!((*this)._bitfield_1),
                30usize,
                2u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set_A_raw(this: *mut Self, val: mfxU32) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 4usize]>>::raw_set(
                ::std::ptr::addr_of_mut!((*this)._bitfield_1),
                30usize,
                2u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        B: mfxU32,
        G: mfxU32,
        R: mfxU32,
        A: mfxU32,
    ) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 10u8, {
            let B: u32 = unsafe { ::std::mem::transmute(B) };
            B as u64
        });
        __bindgen_bitfield_unit.set(10usize, 10u8, {
            let G: u32 = unsafe { ::std::mem::transmute(G) };
            G as u64
        });
        __bindgen_bitfield_unit.set(20usize, 10u8, {
            let R: u32 = unsafe { ::std::mem::transmute(R) };
            R as u64
        });
        __bindgen_bitfield_unit.set(30usize, 2u8, {
            let A: u32 = unsafe { ::std::mem::transmute(A) };
            A as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxABGR16FP {
    pub R: mfxFP16,
    pub G: mfxFP16,
    pub B: mfxFP16,
    pub A: mfxFP16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxABGR16FP"][::std::mem::size_of::<mfxABGR16FP>() - 8usize];
    ["Alignment of mfxABGR16FP"][::std::mem::align_of::<mfxABGR16FP>() - 2usize];
    ["Offset of field: mfxABGR16FP::R"][::std::mem::offset_of!(mfxABGR16FP, R) - 0usize];
    ["Offset of field: mfxABGR16FP::G"][::std::mem::offset_of!(mfxABGR16FP, G) - 2usize];
    ["Offset of field: mfxABGR16FP::B"][::std::mem::offset_of!(mfxABGR16FP, B) - 4usize];
    ["Offset of field: mfxABGR16FP::A"][::std::mem::offset_of!(mfxABGR16FP, A) - 6usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxFrameData {
    pub __bindgen_anon_1: mfxFrameData__bindgen_ty_1,
    pub NumExtParam: mfxU16,
    pub reserved: [mfxU16; 9usize],
    pub MemType: mfxU16,
    pub PitchHigh: mfxU16,
    pub TimeStamp: mfxU64,
    pub FrameOrder: mfxU32,
    pub Locked: mfxU16,
    pub __bindgen_anon_2: mfxFrameData__bindgen_ty_2,
    pub __bindgen_anon_3: mfxFrameData__bindgen_ty_3,
    pub __bindgen_anon_4: mfxFrameData__bindgen_ty_4,
    pub __bindgen_anon_5: mfxFrameData__bindgen_ty_5,
    pub A: *mut mfxU8,
    pub MemId: mfxMemId,
    pub Corrupted: mfxU16,
    pub DataFlag: mfxU16,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxFrameData__bindgen_ty_1 {
    pub ExtParam: *mut *mut mfxExtBuffer,
    pub reserved2: mfxU64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameData__bindgen_ty_1"]
        [::std::mem::size_of::<mfxFrameData__bindgen_ty_1>() - 8usize];
    ["Alignment of mfxFrameData__bindgen_ty_1"]
        [::std::mem::align_of::<mfxFrameData__bindgen_ty_1>() - 8usize];
    ["Offset of field: mfxFrameData__bindgen_ty_1::ExtParam"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_1, ExtParam) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_1::reserved2"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_1, reserved2) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxFrameData__bindgen_ty_2 {
    pub Pitch: mfxU16,
    pub PitchLow: mfxU16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameData__bindgen_ty_2"]
        [::std::mem::size_of::<mfxFrameData__bindgen_ty_2>() - 2usize];
    ["Alignment of mfxFrameData__bindgen_ty_2"]
        [::std::mem::align_of::<mfxFrameData__bindgen_ty_2>() - 2usize];
    ["Offset of field: mfxFrameData__bindgen_ty_2::Pitch"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_2, Pitch) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_2::PitchLow"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_2, PitchLow) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxFrameData__bindgen_ty_3 {
    pub Y: *mut mfxU8,
    pub Y16: *mut mfxU16,
    pub R: *mut mfxU8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameData__bindgen_ty_3"]
        [::std::mem::size_of::<mfxFrameData__bindgen_ty_3>() - 8usize];
    ["Alignment of mfxFrameData__bindgen_ty_3"]
        [::std::mem::align_of::<mfxFrameData__bindgen_ty_3>() - 8usize];
    ["Offset of field: mfxFrameData__bindgen_ty_3::Y"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_3, Y) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_3::Y16"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_3, Y16) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_3::R"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_3, R) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxFrameData__bindgen_ty_4 {
    pub UV: *mut mfxU8,
    pub VU: *mut mfxU8,
    pub CbCr: *mut mfxU8,
    pub CrCb: *mut mfxU8,
    pub Cb: *mut mfxU8,
    pub U: *mut mfxU8,
    pub U16: *mut mfxU16,
    pub G: *mut mfxU8,
    pub Y410: *mut mfxY410,
    pub Y416: *mut mfxY416,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameData__bindgen_ty_4"]
        [::std::mem::size_of::<mfxFrameData__bindgen_ty_4>() - 8usize];
    ["Alignment of mfxFrameData__bindgen_ty_4"]
        [::std::mem::align_of::<mfxFrameData__bindgen_ty_4>() - 8usize];
    ["Offset of field: mfxFrameData__bindgen_ty_4::UV"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_4, UV) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_4::VU"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_4, VU) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_4::CbCr"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_4, CbCr) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_4::CrCb"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_4, CrCb) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_4::Cb"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_4, Cb) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_4::U"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_4, U) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_4::U16"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_4, U16) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_4::G"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_4, G) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_4::Y410"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_4, Y410) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_4::Y416"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_4, Y416) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxFrameData__bindgen_ty_5 {
    pub Cr: *mut mfxU8,
    pub V: *mut mfxU8,
    pub V16: *mut mfxU16,
    pub B: *mut mfxU8,
    pub A2RGB10: *mut mfxA2RGB10,
    pub ABGRFP16: *mut mfxABGR16FP,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameData__bindgen_ty_5"]
        [::std::mem::size_of::<mfxFrameData__bindgen_ty_5>() - 8usize];
    ["Alignment of mfxFrameData__bindgen_ty_5"]
        [::std::mem::align_of::<mfxFrameData__bindgen_ty_5>() - 8usize];
    ["Offset of field: mfxFrameData__bindgen_ty_5::Cr"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_5, Cr) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_5::V"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_5, V) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_5::V16"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_5, V16) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_5::B"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_5, B) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_5::A2RGB10"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_5, A2RGB10) - 0usize];
    ["Offset of field: mfxFrameData__bindgen_ty_5::ABGRFP16"]
        [::std::mem::offset_of!(mfxFrameData__bindgen_ty_5, ABGRFP16) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameData"][::std::mem::size_of::<mfxFrameData>() - 96usize];
    ["Alignment of mfxFrameData"][::std::mem::align_of::<mfxFrameData>() - 8usize];
    ["Offset of field: mfxFrameData::NumExtParam"]
        [::std::mem::offset_of!(mfxFrameData, NumExtParam) - 8usize];
    ["Offset of field: mfxFrameData::reserved"]
        [::std::mem::offset_of!(mfxFrameData, reserved) - 10usize];
    ["Offset of field: mfxFrameData::MemType"]
        [::std::mem::offset_of!(mfxFrameData, MemType) - 28usize];
    ["Offset of field: mfxFrameData::PitchHigh"]
        [::std::mem::offset_of!(mfxFrameData, PitchHigh) - 30usize];
    ["Offset of field: mfxFrameData::TimeStamp"]
        [::std::mem::offset_of!(mfxFrameData, TimeStamp) - 32usize];
    ["Offset of field: mfxFrameData::FrameOrder"]
        [::std::mem::offset_of!(mfxFrameData, FrameOrder) - 40usize];
    ["Offset of field: mfxFrameData::Locked"]
        [::std::mem::offset_of!(mfxFrameData, Locked) - 44usize];
    ["Offset of field: mfxFrameData::A"][::std::mem::offset_of!(mfxFrameData, A) - 72usize];
    ["Offset of field: mfxFrameData::MemId"][::std::mem::offset_of!(mfxFrameData, MemId) - 80usize];
    ["Offset of field: mfxFrameData::Corrupted"]
        [::std::mem::offset_of!(mfxFrameData, Corrupted) - 88usize];
    ["Offset of field: mfxFrameData::DataFlag"]
        [::std::mem::offset_of!(mfxFrameData, DataFlag) - 90usize];
};
pub const MFX_HANDLE_DIRECT3D_DEVICE_MANAGER9: mfxHandleType = 1;
pub const MFX_HANDLE_D3D9_DEVICE_MANAGER: mfxHandleType = 1;
pub const MFX_HANDLE_RESERVED1: mfxHandleType = 2;
pub const MFX_HANDLE_D3D11_DEVICE: mfxHandleType = 3;
pub const MFX_HANDLE_VA_DISPLAY: mfxHandleType = 4;
pub const MFX_HANDLE_RESERVED3: mfxHandleType = 5;
pub const MFX_HANDLE_VA_CONFIG_ID: mfxHandleType = 6;
pub const MFX_HANDLE_VA_CONTEXT_ID: mfxHandleType = 7;
pub const MFX_HANDLE_CM_DEVICE: mfxHandleType = 8;
pub const MFX_HANDLE_HDDLUNITE_WORKLOADCONTEXT: mfxHandleType = 9;
pub const MFX_HANDLE_PXP_CONTEXT: mfxHandleType = 10;
pub const MFX_HANDLE_CONFIG_INTERFACE: mfxHandleType = 1000;
pub type mfxHandleType = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxFrameSurface1 {
    pub __bindgen_anon_1: mfxFrameSurface1__bindgen_ty_1,
    pub Version: mfxStructVersion,
    pub reserved1: [mfxU16; 3usize],
    pub Info: mfxFrameInfo,
    pub Data: mfxFrameData,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxFrameSurface1__bindgen_ty_1 {
    pub FrameInterface: *mut mfxFrameSurfaceInterface,
    pub reserved: [mfxU32; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameSurface1__bindgen_ty_1"]
        [::std::mem::size_of::<mfxFrameSurface1__bindgen_ty_1>() - 8usize];
    ["Alignment of mfxFrameSurface1__bindgen_ty_1"]
        [::std::mem::align_of::<mfxFrameSurface1__bindgen_ty_1>() - 8usize];
    ["Offset of field: mfxFrameSurface1__bindgen_ty_1::FrameInterface"]
        [::std::mem::offset_of!(mfxFrameSurface1__bindgen_ty_1, FrameInterface) - 0usize];
    ["Offset of field: mfxFrameSurface1__bindgen_ty_1::reserved"]
        [::std::mem::offset_of!(mfxFrameSurface1__bindgen_ty_1, reserved) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameSurface1"][::std::mem::size_of::<mfxFrameSurface1>() - 184usize];
    ["Alignment of mfxFrameSurface1"][::std::mem::align_of::<mfxFrameSurface1>() - 8usize];
    ["Offset of field: mfxFrameSurface1::Version"]
        [::std::mem::offset_of!(mfxFrameSurface1, Version) - 8usize];
    ["Offset of field: mfxFrameSurface1::reserved1"]
        [::std::mem::offset_of!(mfxFrameSurface1, reserved1) - 10usize];
    ["Offset of field: mfxFrameSurface1::Info"]
        [::std::mem::offset_of!(mfxFrameSurface1, Info) - 16usize];
    ["Offset of field: mfxFrameSurface1::Data"]
        [::std::mem::offset_of!(mfxFrameSurface1, Data) - 88usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxFrameSurfaceInterface {
    pub Context: mfxHDL,
    pub Version: mfxStructVersion,
    pub reserved1: [mfxU16; 3usize],
    pub AddRef:
        ::std::option::Option<unsafe extern "C" fn(surface: *mut mfxFrameSurface1) -> mfxStatus>,
    pub Release:
        ::std::option::Option<unsafe extern "C" fn(surface: *mut mfxFrameSurface1) -> mfxStatus>,
    pub GetRefCounter: ::std::option::Option<
        unsafe extern "C" fn(surface: *mut mfxFrameSurface1, counter: *mut mfxU32) -> mfxStatus,
    >,
    pub Map: ::std::option::Option<
        unsafe extern "C" fn(surface: *mut mfxFrameSurface1, flags: mfxU32) -> mfxStatus,
    >,
    pub Unmap:
        ::std::option::Option<unsafe extern "C" fn(surface: *mut mfxFrameSurface1) -> mfxStatus>,
    pub GetNativeHandle: ::std::option::Option<
        unsafe extern "C" fn(
            surface: *mut mfxFrameSurface1,
            resource: *mut mfxHDL,
            resource_type: *mut mfxResourceType,
        ) -> mfxStatus,
    >,
    pub GetDeviceHandle: ::std::option::Option<
        unsafe extern "C" fn(
            surface: *mut mfxFrameSurface1,
            device_handle: *mut mfxHDL,
            device_type: *mut mfxHandleType,
        ) -> mfxStatus,
    >,
    pub Synchronize: ::std::option::Option<
        unsafe extern "C" fn(surface: *mut mfxFrameSurface1, wait: mfxU32) -> mfxStatus,
    >,
    pub OnComplete: ::std::option::Option<unsafe extern "C" fn(sts: mfxStatus)>,
    pub QueryInterface: ::std::option::Option<
        unsafe extern "C" fn(
            surface: *mut mfxFrameSurface1,
            guid: mfxGUID,
            iface: *mut mfxHDL,
        ) -> mfxStatus,
    >,
    pub reserved2: [mfxHDL; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameSurfaceInterface"]
        [::std::mem::size_of::<mfxFrameSurfaceInterface>() - 112usize];
    ["Alignment of mfxFrameSurfaceInterface"]
        [::std::mem::align_of::<mfxFrameSurfaceInterface>() - 8usize];
    ["Offset of field: mfxFrameSurfaceInterface::Context"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, Context) - 0usize];
    ["Offset of field: mfxFrameSurfaceInterface::Version"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, Version) - 8usize];
    ["Offset of field: mfxFrameSurfaceInterface::reserved1"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, reserved1) - 10usize];
    ["Offset of field: mfxFrameSurfaceInterface::AddRef"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, AddRef) - 16usize];
    ["Offset of field: mfxFrameSurfaceInterface::Release"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, Release) - 24usize];
    ["Offset of field: mfxFrameSurfaceInterface::GetRefCounter"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, GetRefCounter) - 32usize];
    ["Offset of field: mfxFrameSurfaceInterface::Map"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, Map) - 40usize];
    ["Offset of field: mfxFrameSurfaceInterface::Unmap"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, Unmap) - 48usize];
    ["Offset of field: mfxFrameSurfaceInterface::GetNativeHandle"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, GetNativeHandle) - 56usize];
    ["Offset of field: mfxFrameSurfaceInterface::GetDeviceHandle"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, GetDeviceHandle) - 64usize];
    ["Offset of field: mfxFrameSurfaceInterface::Synchronize"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, Synchronize) - 72usize];
    ["Offset of field: mfxFrameSurfaceInterface::OnComplete"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, OnComplete) - 80usize];
    ["Offset of field: mfxFrameSurfaceInterface::QueryInterface"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, QueryInterface) - 88usize];
    ["Offset of field: mfxFrameSurfaceInterface::reserved2"]
        [::std::mem::offset_of!(mfxFrameSurfaceInterface, reserved2) - 96usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxInfoMFX {
    pub reserved: [mfxU32; 7usize],
    pub LowPower: mfxU16,
    pub BRCParamMultiplier: mfxU16,
    pub FrameInfo: mfxFrameInfo,
    pub CodecId: mfxU32,
    pub CodecProfile: mfxU16,
    pub CodecLevel: mfxU16,
    pub NumThread: mfxU16,
    pub __bindgen_anon_1: mfxInfoMFX__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxInfoMFX__bindgen_ty_1 {
    pub __bindgen_anon_1: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1,
    pub __bindgen_anon_2: mfxInfoMFX__bindgen_ty_1__bindgen_ty_2,
    pub __bindgen_anon_3: mfxInfoMFX__bindgen_ty_1__bindgen_ty_3,
    pub __bindgen_anon_4: mfxInfoMFX__bindgen_ty_1__bindgen_ty_4,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxInfoMFX__bindgen_ty_1__bindgen_ty_1 {
    pub TargetUsage: mfxU16,
    pub GopPicSize: mfxU16,
    pub GopRefDist: mfxU16,
    pub GopOptFlag: mfxU16,
    pub IdrInterval: mfxU16,
    pub RateControlMethod: mfxU16,
    pub __bindgen_anon_1: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1,
    pub BufferSizeInKB: mfxU16,
    pub __bindgen_anon_2: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2,
    pub __bindgen_anon_3: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3,
    pub NumSlice: mfxU16,
    pub NumRefFrame: mfxU16,
    pub EncodedOrder: mfxU16,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1 {
    pub InitialDelayInKB: mfxU16,
    pub QPI: mfxU16,
    pub Accuracy: mfxU16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1>() - 2usize];
    ["Alignment of mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1>() - 2usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1::InitialDelayInKB"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1,
        InitialDelayInKB
    )
        - 0usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1::QPI"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1,
        QPI
    ) - 0usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1::Accuracy"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1,
        Accuracy
    ) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2 {
    pub TargetKbps: mfxU16,
    pub QPP: mfxU16,
    pub ICQQuality: mfxU16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2>() - 2usize];
    ["Alignment of mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2>() - 2usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2::TargetKbps"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2,
        TargetKbps
    )
        - 0usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2::QPP"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2,
        QPP
    ) - 0usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2::ICQQuality"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_2,
        ICQQuality
    )
        - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3 {
    pub MaxKbps: mfxU16,
    pub QPB: mfxU16,
    pub Convergence: mfxU16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::size_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3>() - 2usize];
    ["Alignment of mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::align_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3>() - 2usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3::MaxKbps"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3,
        MaxKbps
    ) - 0usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3::QPB"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3,
        QPB
    ) - 0usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3::Convergence"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_1__bindgen_ty_3,
        Convergence
    )
        - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInfoMFX__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_1>() - 26usize];
    ["Alignment of mfxInfoMFX__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_1>() - 2usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1::TargetUsage"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_1, TargetUsage) - 0usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1::GopPicSize"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_1, GopPicSize) - 2usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1::GopRefDist"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_1, GopRefDist) - 4usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1::GopOptFlag"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_1, GopOptFlag) - 6usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1::IdrInterval"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_1, IdrInterval) - 8usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1::RateControlMethod"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_1,
        RateControlMethod
    ) - 10usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1::BufferSizeInKB"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_1, BufferSizeInKB) - 14usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1::NumSlice"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_1, NumSlice) - 20usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1::NumRefFrame"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_1, NumRefFrame) - 22usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_1::EncodedOrder"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_1, EncodedOrder) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxInfoMFX__bindgen_ty_1__bindgen_ty_2 {
    pub DecodedOrder: mfxU16,
    pub ExtendedPicStruct: mfxU16,
    pub TimeStampCalc: mfxU16,
    pub SliceGroupsPresent: mfxU16,
    pub MaxDecFrameBuffering: mfxU16,
    pub EnableReallocRequest: mfxU16,
    pub FilmGrain: mfxU16,
    pub IgnoreLevelConstrain: mfxU16,
    pub SkipOutput: mfxU16,
    pub reserved2: [mfxU16; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInfoMFX__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_2>() - 26usize];
    ["Alignment of mfxInfoMFX__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_2>() - 2usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_2::DecodedOrder"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_2, DecodedOrder) - 0usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_2::ExtendedPicStruct"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_2,
        ExtendedPicStruct
    ) - 2usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_2::TimeStampCalc"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_2, TimeStampCalc) - 4usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_2::SliceGroupsPresent"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_2,
        SliceGroupsPresent
    ) - 6usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_2::MaxDecFrameBuffering"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_2,
        MaxDecFrameBuffering
    ) - 8usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_2::EnableReallocRequest"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_2,
        EnableReallocRequest
    ) - 10usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_2::FilmGrain"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_2, FilmGrain) - 12usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_2::IgnoreLevelConstrain"][::std::mem::offset_of!(
        mfxInfoMFX__bindgen_ty_1__bindgen_ty_2,
        IgnoreLevelConstrain
    ) - 14usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_2::SkipOutput"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_2, SkipOutput) - 16usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_2::reserved2"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_2, reserved2) - 18usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxInfoMFX__bindgen_ty_1__bindgen_ty_3 {
    pub JPEGChromaFormat: mfxU16,
    pub Rotation: mfxU16,
    pub JPEGColorFormat: mfxU16,
    pub InterleavedDec: mfxU16,
    pub SamplingFactorH: [mfxU8; 4usize],
    pub SamplingFactorV: [mfxU8; 4usize],
    pub reserved3: [mfxU16; 5usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInfoMFX__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::size_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_3>() - 26usize];
    ["Alignment of mfxInfoMFX__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::align_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_3>() - 2usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_3::JPEGChromaFormat"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_3, JPEGChromaFormat) - 0usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_3::Rotation"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_3, Rotation) - 2usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_3::JPEGColorFormat"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_3, JPEGColorFormat) - 4usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_3::InterleavedDec"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_3, InterleavedDec) - 6usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_3::SamplingFactorH"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_3, SamplingFactorH) - 8usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_3::SamplingFactorV"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_3, SamplingFactorV) - 12usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_3::reserved3"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_3, reserved3) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mfxInfoMFX__bindgen_ty_1__bindgen_ty_4 {
    pub Interleaved: mfxU16,
    pub Quality: mfxU16,
    pub RestartInterval: mfxU16,
    pub reserved5: [mfxU16; 10usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInfoMFX__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::size_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_4>() - 26usize];
    ["Alignment of mfxInfoMFX__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::align_of::<mfxInfoMFX__bindgen_ty_1__bindgen_ty_4>() - 2usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_4::Interleaved"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_4, Interleaved) - 0usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_4::Quality"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_4, Quality) - 2usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_4::RestartInterval"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_4, RestartInterval) - 4usize];
    ["Offset of field: mfxInfoMFX__bindgen_ty_1__bindgen_ty_4::reserved5"]
        [::std::mem::offset_of!(mfxInfoMFX__bindgen_ty_1__bindgen_ty_4, reserved5) - 6usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInfoMFX__bindgen_ty_1"]
        [::std::mem::size_of::<mfxInfoMFX__bindgen_ty_1>() - 26usize];
    ["Alignment of mfxInfoMFX__bindgen_ty_1"]
        [::std::mem::align_of::<mfxInfoMFX__bindgen_ty_1>() - 2usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInfoMFX"][::std::mem::size_of::<mfxInfoMFX>() - 136usize];
    ["Alignment of mfxInfoMFX"][::std::mem::align_of::<mfxInfoMFX>() - 4usize];
    ["Offset of field: mfxInfoMFX::reserved"]
        [::std::mem::offset_of!(mfxInfoMFX, reserved) - 0usize];
    ["Offset of field: mfxInfoMFX::LowPower"]
        [::std::mem::offset_of!(mfxInfoMFX, LowPower) - 28usize];
    ["Offset of field: mfxInfoMFX::BRCParamMultiplier"]
        [::std::mem::offset_of!(mfxInfoMFX, BRCParamMultiplier) - 30usize];
    ["Offset of field: mfxInfoMFX::FrameInfo"]
        [::std::mem::offset_of!(mfxInfoMFX, FrameInfo) - 32usize];
    ["Offset of field: mfxInfoMFX::CodecId"]
        [::std::mem::offset_of!(mfxInfoMFX, CodecId) - 100usize];
    ["Offset of field: mfxInfoMFX::CodecProfile"]
        [::std::mem::offset_of!(mfxInfoMFX, CodecProfile) - 104usize];
    ["Offset of field: mfxInfoMFX::CodecLevel"]
        [::std::mem::offset_of!(mfxInfoMFX, CodecLevel) - 106usize];
    ["Offset of field: mfxInfoMFX::NumThread"]
        [::std::mem::offset_of!(mfxInfoMFX, NumThread) - 108usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxInfoVPP {
    pub reserved: [mfxU32; 8usize],
    pub In: mfxFrameInfo,
    pub Out: mfxFrameInfo,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxInfoVPP"][::std::mem::size_of::<mfxInfoVPP>() - 168usize];
    ["Alignment of mfxInfoVPP"][::std::mem::align_of::<mfxInfoVPP>() - 4usize];
    ["Offset of field: mfxInfoVPP::reserved"]
        [::std::mem::offset_of!(mfxInfoVPP, reserved) - 0usize];
    ["Offset of field: mfxInfoVPP::In"][::std::mem::offset_of!(mfxInfoVPP, In) - 32usize];
    ["Offset of field: mfxInfoVPP::Out"][::std::mem::offset_of!(mfxInfoVPP, Out) - 100usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxVideoParam {
    pub AllocId: mfxU32,
    pub reserved: [mfxU32; 2usize],
    pub reserved3: mfxU16,
    pub AsyncDepth: mfxU16,
    pub __bindgen_anon_1: mfxVideoParam__bindgen_ty_1,
    pub Protected: mfxU16,
    pub IOPattern: mfxU16,
    pub ExtParam: *mut *mut mfxExtBuffer,
    pub NumExtParam: mfxU16,
    pub reserved2: mfxU16,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxVideoParam__bindgen_ty_1 {
    pub mfx: mfxInfoMFX,
    pub vpp: mfxInfoVPP,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxVideoParam__bindgen_ty_1"]
        [::std::mem::size_of::<mfxVideoParam__bindgen_ty_1>() - 168usize];
    ["Alignment of mfxVideoParam__bindgen_ty_1"]
        [::std::mem::align_of::<mfxVideoParam__bindgen_ty_1>() - 4usize];
    ["Offset of field: mfxVideoParam__bindgen_ty_1::mfx"]
        [::std::mem::offset_of!(mfxVideoParam__bindgen_ty_1, mfx) - 0usize];
    ["Offset of field: mfxVideoParam__bindgen_ty_1::vpp"]
        [::std::mem::offset_of!(mfxVideoParam__bindgen_ty_1, vpp) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxVideoParam"][::std::mem::size_of::<mfxVideoParam>() - 208usize];
    ["Alignment of mfxVideoParam"][::std::mem::align_of::<mfxVideoParam>() - 8usize];
    ["Offset of field: mfxVideoParam::AllocId"]
        [::std::mem::offset_of!(mfxVideoParam, AllocId) - 0usize];
    ["Offset of field: mfxVideoParam::reserved"]
        [::std::mem::offset_of!(mfxVideoParam, reserved) - 4usize];
    ["Offset of field: mfxVideoParam::reserved3"]
        [::std::mem::offset_of!(mfxVideoParam, reserved3) - 12usize];
    ["Offset of field: mfxVideoParam::AsyncDepth"]
        [::std::mem::offset_of!(mfxVideoParam, AsyncDepth) - 14usize];
    ["Offset of field: mfxVideoParam::Protected"]
        [::std::mem::offset_of!(mfxVideoParam, Protected) - 184usize];
    ["Offset of field: mfxVideoParam::IOPattern"]
        [::std::mem::offset_of!(mfxVideoParam, IOPattern) - 186usize];
    ["Offset of field: mfxVideoParam::ExtParam"]
        [::std::mem::offset_of!(mfxVideoParam, ExtParam) - 192usize];
    ["Offset of field: mfxVideoParam::NumExtParam"]
        [::std::mem::offset_of!(mfxVideoParam, NumExtParam) - 200usize];
    ["Offset of field: mfxVideoParam::reserved2"]
        [::std::mem::offset_of!(mfxVideoParam, reserved2) - 202usize];
};
pub const MFX_IOPATTERN_IN_VIDEO_MEMORY: _bindgen_ty_13 = 1;
pub const MFX_IOPATTERN_IN_SYSTEM_MEMORY: _bindgen_ty_13 = 2;
pub const MFX_IOPATTERN_OUT_VIDEO_MEMORY: _bindgen_ty_13 = 16;
pub const MFX_IOPATTERN_OUT_SYSTEM_MEMORY: _bindgen_ty_13 = 32;
pub type _bindgen_ty_13 = ::std::os::raw::c_int;
pub const MFX_CODEC_AVC: _bindgen_ty_14 = 541283905;
pub const MFX_CODEC_HEVC: _bindgen_ty_14 = 1129727304;
pub const MFX_CODEC_MPEG2: _bindgen_ty_14 = 843534413;
pub const MFX_CODEC_VC1: _bindgen_ty_14 = 540099414;
pub const MFX_CODEC_CAPTURE: _bindgen_ty_14 = 1414545731;
pub const MFX_CODEC_VP9: _bindgen_ty_14 = 540627030;
pub const MFX_CODEC_AV1: _bindgen_ty_14 = 540104257;
pub const MFX_CODEC_VVC: _bindgen_ty_14 = 541283926;
pub type _bindgen_ty_14 = ::std::os::raw::c_int;
pub const MFX_PROFILE_UNKNOWN: _bindgen_ty_15 = 0;
pub const MFX_LEVEL_UNKNOWN: _bindgen_ty_15 = 0;
pub const MFX_PROFILE_AVC_CONSTRAINT_SET0: _bindgen_ty_15 = 256;
pub const MFX_PROFILE_AVC_CONSTRAINT_SET1: _bindgen_ty_15 = 512;
pub const MFX_PROFILE_AVC_CONSTRAINT_SET2: _bindgen_ty_15 = 1024;
pub const MFX_PROFILE_AVC_CONSTRAINT_SET3: _bindgen_ty_15 = 2048;
pub const MFX_PROFILE_AVC_CONSTRAINT_SET4: _bindgen_ty_15 = 4096;
pub const MFX_PROFILE_AVC_CONSTRAINT_SET5: _bindgen_ty_15 = 8192;
pub const MFX_PROFILE_AVC_BASELINE: _bindgen_ty_15 = 66;
pub const MFX_PROFILE_AVC_MAIN: _bindgen_ty_15 = 77;
pub const MFX_PROFILE_AVC_EXTENDED: _bindgen_ty_15 = 88;
pub const MFX_PROFILE_AVC_HIGH: _bindgen_ty_15 = 100;
pub const MFX_PROFILE_AVC_HIGH10: _bindgen_ty_15 = 110;
pub const MFX_PROFILE_AVC_HIGH_422: _bindgen_ty_15 = 122;
pub const MFX_PROFILE_AVC_CONSTRAINED_BASELINE: _bindgen_ty_15 = 578;
pub const MFX_PROFILE_AVC_CONSTRAINED_HIGH: _bindgen_ty_15 = 12388;
pub const MFX_PROFILE_AVC_PROGRESSIVE_HIGH: _bindgen_ty_15 = 4196;
pub const MFX_LEVEL_AVC_1: _bindgen_ty_15 = 10;
pub const MFX_LEVEL_AVC_1b: _bindgen_ty_15 = 9;
pub const MFX_LEVEL_AVC_11: _bindgen_ty_15 = 11;
pub const MFX_LEVEL_AVC_12: _bindgen_ty_15 = 12;
pub const MFX_LEVEL_AVC_13: _bindgen_ty_15 = 13;
pub const MFX_LEVEL_AVC_2: _bindgen_ty_15 = 20;
pub const MFX_LEVEL_AVC_21: _bindgen_ty_15 = 21;
pub const MFX_LEVEL_AVC_22: _bindgen_ty_15 = 22;
pub const MFX_LEVEL_AVC_3: _bindgen_ty_15 = 30;
pub const MFX_LEVEL_AVC_31: _bindgen_ty_15 = 31;
pub const MFX_LEVEL_AVC_32: _bindgen_ty_15 = 32;
pub const MFX_LEVEL_AVC_4: _bindgen_ty_15 = 40;
pub const MFX_LEVEL_AVC_41: _bindgen_ty_15 = 41;
pub const MFX_LEVEL_AVC_42: _bindgen_ty_15 = 42;
pub const MFX_LEVEL_AVC_5: _bindgen_ty_15 = 50;
pub const MFX_LEVEL_AVC_51: _bindgen_ty_15 = 51;
pub const MFX_LEVEL_AVC_52: _bindgen_ty_15 = 52;
pub const MFX_LEVEL_AVC_6: _bindgen_ty_15 = 60;
pub const MFX_LEVEL_AVC_61: _bindgen_ty_15 = 61;
pub const MFX_LEVEL_AVC_62: _bindgen_ty_15 = 62;
pub const MFX_PROFILE_MPEG2_SIMPLE: _bindgen_ty_15 = 80;
pub const MFX_PROFILE_MPEG2_MAIN: _bindgen_ty_15 = 64;
pub const MFX_PROFILE_MPEG2_HIGH: _bindgen_ty_15 = 16;
pub const MFX_LEVEL_MPEG2_LOW: _bindgen_ty_15 = 10;
pub const MFX_LEVEL_MPEG2_MAIN: _bindgen_ty_15 = 8;
pub const MFX_LEVEL_MPEG2_HIGH: _bindgen_ty_15 = 4;
pub const MFX_LEVEL_MPEG2_HIGH1440: _bindgen_ty_15 = 6;
pub const MFX_PROFILE_VC1_SIMPLE: _bindgen_ty_15 = 1;
pub const MFX_PROFILE_VC1_MAIN: _bindgen_ty_15 = 5;
pub const MFX_PROFILE_VC1_ADVANCED: _bindgen_ty_15 = 13;
pub const MFX_LEVEL_VC1_LOW: _bindgen_ty_15 = 1;
pub const MFX_LEVEL_VC1_MEDIAN: _bindgen_ty_15 = 3;
pub const MFX_LEVEL_VC1_HIGH: _bindgen_ty_15 = 5;
pub const MFX_LEVEL_VC1_0: _bindgen_ty_15 = 1;
pub const MFX_LEVEL_VC1_1: _bindgen_ty_15 = 2;
pub const MFX_LEVEL_VC1_2: _bindgen_ty_15 = 3;
pub const MFX_LEVEL_VC1_3: _bindgen_ty_15 = 4;
pub const MFX_LEVEL_VC1_4: _bindgen_ty_15 = 5;
pub const MFX_PROFILE_HEVC_MAIN: _bindgen_ty_15 = 1;
pub const MFX_PROFILE_HEVC_MAIN10: _bindgen_ty_15 = 2;
pub const MFX_PROFILE_HEVC_MAINSP: _bindgen_ty_15 = 3;
pub const MFX_PROFILE_HEVC_REXT: _bindgen_ty_15 = 4;
pub const MFX_PROFILE_HEVC_SCC: _bindgen_ty_15 = 9;
pub const MFX_LEVEL_HEVC_1: _bindgen_ty_15 = 10;
pub const MFX_LEVEL_HEVC_2: _bindgen_ty_15 = 20;
pub const MFX_LEVEL_HEVC_21: _bindgen_ty_15 = 21;
pub const MFX_LEVEL_HEVC_3: _bindgen_ty_15 = 30;
pub const MFX_LEVEL_HEVC_31: _bindgen_ty_15 = 31;
pub const MFX_LEVEL_HEVC_4: _bindgen_ty_15 = 40;
pub const MFX_LEVEL_HEVC_41: _bindgen_ty_15 = 41;
pub const MFX_LEVEL_HEVC_5: _bindgen_ty_15 = 50;
pub const MFX_LEVEL_HEVC_51: _bindgen_ty_15 = 51;
pub const MFX_LEVEL_HEVC_52: _bindgen_ty_15 = 52;
pub const MFX_LEVEL_HEVC_6: _bindgen_ty_15 = 60;
pub const MFX_LEVEL_HEVC_61: _bindgen_ty_15 = 61;
pub const MFX_LEVEL_HEVC_62: _bindgen_ty_15 = 62;
pub const MFX_LEVEL_HEVC_85: _bindgen_ty_15 = 85;
pub const MFX_TIER_HEVC_MAIN: _bindgen_ty_15 = 0;
pub const MFX_TIER_HEVC_HIGH: _bindgen_ty_15 = 256;
pub const MFX_PROFILE_VP9_0: _bindgen_ty_15 = 1;
pub const MFX_PROFILE_VP9_1: _bindgen_ty_15 = 2;
pub const MFX_PROFILE_VP9_2: _bindgen_ty_15 = 3;
pub const MFX_PROFILE_VP9_3: _bindgen_ty_15 = 4;
pub const MFX_PROFILE_AV1_MAIN: _bindgen_ty_15 = 1;
pub const MFX_PROFILE_AV1_HIGH: _bindgen_ty_15 = 2;
pub const MFX_PROFILE_AV1_PRO: _bindgen_ty_15 = 3;
pub const MFX_LEVEL_AV1_2: _bindgen_ty_15 = 20;
pub const MFX_LEVEL_AV1_21: _bindgen_ty_15 = 21;
pub const MFX_LEVEL_AV1_22: _bindgen_ty_15 = 22;
pub const MFX_LEVEL_AV1_23: _bindgen_ty_15 = 23;
pub const MFX_LEVEL_AV1_3: _bindgen_ty_15 = 30;
pub const MFX_LEVEL_AV1_31: _bindgen_ty_15 = 31;
pub const MFX_LEVEL_AV1_32: _bindgen_ty_15 = 32;
pub const MFX_LEVEL_AV1_33: _bindgen_ty_15 = 33;
pub const MFX_LEVEL_AV1_4: _bindgen_ty_15 = 40;
pub const MFX_LEVEL_AV1_41: _bindgen_ty_15 = 41;
pub const MFX_LEVEL_AV1_42: _bindgen_ty_15 = 42;
pub const MFX_LEVEL_AV1_43: _bindgen_ty_15 = 43;
pub const MFX_LEVEL_AV1_5: _bindgen_ty_15 = 50;
pub const MFX_LEVEL_AV1_51: _bindgen_ty_15 = 51;
pub const MFX_LEVEL_AV1_52: _bindgen_ty_15 = 52;
pub const MFX_LEVEL_AV1_53: _bindgen_ty_15 = 53;
pub const MFX_LEVEL_AV1_6: _bindgen_ty_15 = 60;
pub const MFX_LEVEL_AV1_61: _bindgen_ty_15 = 61;
pub const MFX_LEVEL_AV1_62: _bindgen_ty_15 = 62;
pub const MFX_LEVEL_AV1_63: _bindgen_ty_15 = 63;
pub const MFX_LEVEL_AV1_7: _bindgen_ty_15 = 70;
pub const MFX_LEVEL_AV1_71: _bindgen_ty_15 = 71;
pub const MFX_LEVEL_AV1_72: _bindgen_ty_15 = 72;
pub const MFX_LEVEL_AV1_73: _bindgen_ty_15 = 73;
pub const MFX_PROFILE_VVC_MAIN10: _bindgen_ty_15 = 1;
pub const MFX_PROFILE_VVC_MAIN10_STILL_PICTURE: _bindgen_ty_15 = 65;
pub const MFX_LEVEL_VVC_1: _bindgen_ty_15 = 16;
pub const MFX_LEVEL_VVC_2: _bindgen_ty_15 = 32;
pub const MFX_LEVEL_VVC_21: _bindgen_ty_15 = 35;
pub const MFX_LEVEL_VVC_3: _bindgen_ty_15 = 48;
pub const MFX_LEVEL_VVC_31: _bindgen_ty_15 = 51;
pub const MFX_LEVEL_VVC_4: _bindgen_ty_15 = 64;
pub const MFX_LEVEL_VVC_41: _bindgen_ty_15 = 67;
pub const MFX_LEVEL_VVC_5: _bindgen_ty_15 = 80;
pub const MFX_LEVEL_VVC_51: _bindgen_ty_15 = 83;
pub const MFX_LEVEL_VVC_52: _bindgen_ty_15 = 86;
pub const MFX_LEVEL_VVC_6: _bindgen_ty_15 = 96;
pub const MFX_LEVEL_VVC_61: _bindgen_ty_15 = 99;
pub const MFX_LEVEL_VVC_62: _bindgen_ty_15 = 102;
pub const MFX_LEVEL_VVC_63: _bindgen_ty_15 = 105;
pub const MFX_LEVEL_VVC_155: _bindgen_ty_15 = 255;
pub const MFX_TIER_VVC_MAIN: _bindgen_ty_15 = 0;
pub const MFX_TIER_VVC_HIGH: _bindgen_ty_15 = 256;
pub type _bindgen_ty_15 = ::std::os::raw::c_int;
pub const MFX_BITSTREAM_NO_FLAG: _bindgen_ty_32 = 0;
pub const MFX_BITSTREAM_COMPLETE_FRAME: _bindgen_ty_32 = 1;
pub const MFX_BITSTREAM_EOS: _bindgen_ty_32 = 2;
pub type _bindgen_ty_32 = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mfxFrameAllocRequest {
    pub __bindgen_anon_1: mfxFrameAllocRequest__bindgen_ty_1,
    pub reserved3: [mfxU32; 3usize],
    pub Info: mfxFrameInfo,
    pub Type: mfxU16,
    pub NumFrameMin: mfxU16,
    pub NumFrameSuggested: mfxU16,
    pub reserved2: mfxU16,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mfxFrameAllocRequest__bindgen_ty_1 {
    pub AllocId: mfxU32,
    pub reserved: [mfxU32; 1usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameAllocRequest__bindgen_ty_1"]
        [::std::mem::size_of::<mfxFrameAllocRequest__bindgen_ty_1>() - 4usize];
    ["Alignment of mfxFrameAllocRequest__bindgen_ty_1"]
        [::std::mem::align_of::<mfxFrameAllocRequest__bindgen_ty_1>() - 4usize];
    ["Offset of field: mfxFrameAllocRequest__bindgen_ty_1::AllocId"]
        [::std::mem::offset_of!(mfxFrameAllocRequest__bindgen_ty_1, AllocId) - 0usize];
    ["Offset of field: mfxFrameAllocRequest__bindgen_ty_1::reserved"]
        [::std::mem::offset_of!(mfxFrameAllocRequest__bindgen_ty_1, reserved) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mfxFrameAllocRequest"][::std::mem::size_of::<mfxFrameAllocRequest>() - 92usize];
    ["Alignment of mfxFrameAllocRequest"][::std::mem::align_of::<mfxFrameAllocRequest>() - 4usize];
    ["Offset of field: mfxFrameAllocRequest::reserved3"]
        [::std::mem::offset_of!(mfxFrameAllocRequest, reserved3) - 4usize];
    ["Offset of field: mfxFrameAllocRequest::Info"]
        [::std::mem::offset_of!(mfxFrameAllocRequest, Info) - 16usize];
    ["Offset of field: mfxFrameAllocRequest::Type"]
        [::std::mem::offset_of!(mfxFrameAllocRequest, Type) - 84usize];
    ["Offset of field: mfxFrameAllocRequest::NumFrameMin"]
        [::std::mem::offset_of!(mfxFrameAllocRequest, NumFrameMin) - 86usize];
    ["Offset of field: mfxFrameAllocRequest::NumFrameSuggested"]
        [::std::mem::offset_of!(mfxFrameAllocRequest, NumFrameSuggested) - 88usize];
    ["Offset of field: mfxFrameAllocRequest::reserved2"]
        [::std::mem::offset_of!(mfxFrameAllocRequest, reserved2) - 90usize];
};
