/* automatically generated by rust-bindgen 0.72.1 */

pub const CUDA_VERSION: u32 = 7050;
pub const CU_CTX_SCHED_BLOCKING_SYNC: u32 = 4;
pub const CU_EGL_FRAME_MAX_PLANES: u32 = 3;
pub const CU_STREAM_DEFAULT: u32 = 0;
pub const CU_STREAM_NON_BLOCKING: u32 = 1;
pub const CU_EVENT_DEFAULT: u32 = 0;
pub const CU_EVENT_BLOCKING_SYNC: u32 = 1;
pub const CU_EVENT_DISABLE_TIMING: u32 = 2;
pub const CU_EVENT_WAIT_DEFAULT: u32 = 0;
pub const CU_EVENT_WAIT_EXTERNAL: u32 = 1;
pub const CU_TRSF_READ_AS_INTEGER: u32 = 1;
pub type CUdevice = ::std::os::raw::c_int;
pub type CUdeviceptr = ::std::os::raw::c_ulonglong;
pub type CUtexObject = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUarray_st {
    _unused: [u8; 0],
}
pub type CUarray = *mut CUarray_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUctx_st {
    _unused: [u8; 0],
}
pub type CUcontext = *mut CUctx_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUstream_st {
    _unused: [u8; 0],
}
pub type CUstream = *mut CUstream_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUevent_st {
    _unused: [u8; 0],
}
pub type CUevent = *mut CUevent_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUfunc_st {
    _unused: [u8; 0],
}
pub type CUfunction = *mut CUfunc_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUmod_st {
    _unused: [u8; 0],
}
pub type CUmodule = *mut CUmod_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUmipmappedArray_st {
    _unused: [u8; 0],
}
pub type CUmipmappedArray = *mut CUmipmappedArray_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUgraphicsResource_st {
    _unused: [u8; 0],
}
pub type CUgraphicsResource = *mut CUgraphicsResource_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUextMemory_st {
    _unused: [u8; 0],
}
pub type CUexternalMemory = *mut CUextMemory_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUextSemaphore_st {
    _unused: [u8; 0],
}
pub type CUexternalSemaphore = *mut CUextSemaphore_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUeglStreamConnection_st {
    _unused: [u8; 0],
}
pub type CUeglStreamConnection = *mut CUeglStreamConnection_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUlinkState_st {
    _unused: [u8; 0],
}
pub type CUlinkState = *mut CUlinkState_st;
pub const CUDA_SUCCESS: cudaError_enum = 0;
pub const CUDA_ERROR_NOT_READY: cudaError_enum = 600;
pub const CUDA_ERROR_LAUNCH_TIMEOUT: cudaError_enum = 702;
pub const CUDA_ERROR_UNKNOWN: cudaError_enum = 999;
pub type cudaError_enum = ::std::os::raw::c_uint;
pub use self::cudaError_enum as CUresult;
pub const CU_DEVICE_ATTRIBUTE_CLOCK_RATE: CUdevice_attribute_enum = 13;
pub const CU_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT: CUdevice_attribute_enum = 14;
pub const CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT: CUdevice_attribute_enum = 16;
pub const CU_DEVICE_ATTRIBUTE_INTEGRATED: CUdevice_attribute_enum = 18;
pub const CU_DEVICE_ATTRIBUTE_CAN_MAP_HOST_MEMORY: CUdevice_attribute_enum = 19;
pub const CU_DEVICE_ATTRIBUTE_COMPUTE_MODE: CUdevice_attribute_enum = 20;
pub const CU_DEVICE_ATTRIBUTE_CONCURRENT_KERNELS: CUdevice_attribute_enum = 31;
pub const CU_DEVICE_ATTRIBUTE_PCI_BUS_ID: CUdevice_attribute_enum = 33;
pub const CU_DEVICE_ATTRIBUTE_PCI_DEVICE_ID: CUdevice_attribute_enum = 34;
pub const CU_DEVICE_ATTRIBUTE_TCC_DRIVER: CUdevice_attribute_enum = 35;
pub const CU_DEVICE_ATTRIBUTE_MEMORY_CLOCK_RATE: CUdevice_attribute_enum = 36;
pub const CU_DEVICE_ATTRIBUTE_GLOBAL_MEMORY_BUS_WIDTH: CUdevice_attribute_enum = 37;
pub const CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT: CUdevice_attribute_enum = 40;
pub const CU_DEVICE_ATTRIBUTE_UNIFIED_ADDRESSING: CUdevice_attribute_enum = 41;
pub const CU_DEVICE_ATTRIBUTE_PCI_DOMAIN_ID: CUdevice_attribute_enum = 50;
pub const CU_DEVICE_ATTRIBUTE_TEXTURE_PITCH_ALIGNMENT: CUdevice_attribute_enum = 51;
pub const CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR: CUdevice_attribute_enum = 75;
pub const CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR: CUdevice_attribute_enum = 76;
pub const CU_DEVICE_ATTRIBUTE_MANAGED_MEMORY: CUdevice_attribute_enum = 83;
pub const CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD: CUdevice_attribute_enum = 84;
pub const CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD_GROUP_ID: CUdevice_attribute_enum = 85;
pub type CUdevice_attribute_enum = ::std::os::raw::c_uint;
pub use self::CUdevice_attribute_enum as CUdevice_attribute;
pub const CU_AD_FORMAT_UNSIGNED_INT8: CUarray_format_enum = 1;
pub const CU_AD_FORMAT_UNSIGNED_INT16: CUarray_format_enum = 2;
pub const CU_AD_FORMAT_UNSIGNED_INT32: CUarray_format_enum = 3;
pub const CU_AD_FORMAT_SIGNED_INT8: CUarray_format_enum = 8;
pub const CU_AD_FORMAT_SIGNED_INT16: CUarray_format_enum = 9;
pub const CU_AD_FORMAT_SIGNED_INT32: CUarray_format_enum = 10;
pub const CU_AD_FORMAT_HALF: CUarray_format_enum = 16;
pub const CU_AD_FORMAT_FLOAT: CUarray_format_enum = 32;
pub type CUarray_format_enum = ::std::os::raw::c_uint;
pub use self::CUarray_format_enum as CUarray_format;
pub const CU_MEMORYTYPE_HOST: CUmemorytype_enum = 1;
pub const CU_MEMORYTYPE_DEVICE: CUmemorytype_enum = 2;
pub const CU_MEMORYTYPE_ARRAY: CUmemorytype_enum = 3;
pub type CUmemorytype_enum = ::std::os::raw::c_uint;
pub use self::CUmemorytype_enum as CUmemorytype;
pub const CU_LIMIT_STACK_SIZE: CUlimit_enum = 0;
pub const CU_LIMIT_PRINTF_FIFO_SIZE: CUlimit_enum = 1;
pub const CU_LIMIT_MALLOC_HEAP_SIZE: CUlimit_enum = 2;
pub const CU_LIMIT_DEV_RUNTIME_SYNC_DEPTH: CUlimit_enum = 3;
pub const CU_LIMIT_DEV_RUNTIME_PENDING_LAUNCH_COUNT: CUlimit_enum = 4;
pub type CUlimit_enum = ::std::os::raw::c_uint;
pub use self::CUlimit_enum as CUlimit;
pub const CU_RESOURCE_TYPE_ARRAY: CUresourcetype_enum = 0;
pub const CU_RESOURCE_TYPE_MIPMAPPED_ARRAY: CUresourcetype_enum = 1;
pub const CU_RESOURCE_TYPE_LINEAR: CUresourcetype_enum = 2;
pub const CU_RESOURCE_TYPE_PITCH2D: CUresourcetype_enum = 3;
pub type CUresourcetype_enum = ::std::os::raw::c_uint;
pub use self::CUresourcetype_enum as CUresourcetype;
pub const CU_TR_ADDRESS_MODE_WRAP: CUaddress_mode_enum = 0;
pub const CU_TR_ADDRESS_MODE_CLAMP: CUaddress_mode_enum = 1;
pub const CU_TR_ADDRESS_MODE_MIRROR: CUaddress_mode_enum = 2;
pub const CU_TR_ADDRESS_MODE_BORDER: CUaddress_mode_enum = 3;
pub type CUaddress_mode_enum = ::std::os::raw::c_uint;
pub use self::CUaddress_mode_enum as CUaddress_mode;
pub const CU_TR_FILTER_MODE_POINT: CUfilter_mode_enum = 0;
pub const CU_TR_FILTER_MODE_LINEAR: CUfilter_mode_enum = 1;
pub type CUfilter_mode_enum = ::std::os::raw::c_uint;
pub use self::CUfilter_mode_enum as CUfilter_mode;
pub const CU_GRAPHICS_REGISTER_FLAGS_NONE: CUgraphicsRegisterFlags_enum = 0;
pub const CU_GRAPHICS_REGISTER_FLAGS_READ_ONLY: CUgraphicsRegisterFlags_enum = 1;
pub const CU_GRAPHICS_REGISTER_FLAGS_WRITE_DISCARD: CUgraphicsRegisterFlags_enum = 2;
pub const CU_GRAPHICS_REGISTER_FLAGS_SURFACE_LDST: CUgraphicsRegisterFlags_enum = 4;
pub const CU_GRAPHICS_REGISTER_FLAGS_TEXTURE_GATHER: CUgraphicsRegisterFlags_enum = 8;
pub type CUgraphicsRegisterFlags_enum = ::std::os::raw::c_uint;
pub use self::CUgraphicsRegisterFlags_enum as CUgraphicsRegisterFlags;
pub const CU_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD: CUexternalMemoryHandleType_enum = 1;
pub const CU_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32: CUexternalMemoryHandleType_enum = 2;
pub const CU_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT: CUexternalMemoryHandleType_enum = 3;
pub const CU_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP: CUexternalMemoryHandleType_enum = 4;
pub const CU_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE: CUexternalMemoryHandleType_enum = 5;
pub type CUexternalMemoryHandleType_enum = ::std::os::raw::c_uint;
pub use self::CUexternalMemoryHandleType_enum as CUexternalMemoryHandleType;
pub const CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD: CUexternalSemaphoreHandleType_enum = 1;
pub const CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32: CUexternalSemaphoreHandleType_enum = 2;
pub const CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT: CUexternalSemaphoreHandleType_enum =
    3;
pub const CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE: CUexternalSemaphoreHandleType_enum = 4;
pub const CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_TIMELINE_SEMAPHORE_FD:
    CUexternalSemaphoreHandleType_enum = 9;
pub const CU_EXTERNAL_SEMAPHORE_HANDLE_TYPE_TIMELINE_SEMAPHORE_WIN32:
    CUexternalSemaphoreHandleType_enum = 10;
pub type CUexternalSemaphoreHandleType_enum = ::std::os::raw::c_uint;
pub use self::CUexternalSemaphoreHandleType_enum as CUexternalSemaphoreHandleType;
pub const CU_JIT_MAX_REGISTERS: CUjit_option_enum = 0;
pub const CU_JIT_THREADS_PER_BLOCK: CUjit_option_enum = 1;
pub const CU_JIT_WALL_TIME: CUjit_option_enum = 2;
pub const CU_JIT_INFO_LOG_BUFFER: CUjit_option_enum = 3;
pub const CU_JIT_INFO_LOG_BUFFER_SIZE_BYTES: CUjit_option_enum = 4;
pub const CU_JIT_ERROR_LOG_BUFFER: CUjit_option_enum = 5;
pub const CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES: CUjit_option_enum = 6;
pub const CU_JIT_OPTIMIZATION_LEVEL: CUjit_option_enum = 7;
pub const CU_JIT_TARGET_FROM_CUCONTEXT: CUjit_option_enum = 8;
pub const CU_JIT_TARGET: CUjit_option_enum = 9;
pub const CU_JIT_FALLBACK_STRATEGY: CUjit_option_enum = 10;
pub const CU_JIT_GENERATE_DEBUG_INFO: CUjit_option_enum = 11;
pub const CU_JIT_LOG_VERBOSE: CUjit_option_enum = 12;
pub const CU_JIT_GENERATE_LINE_INFO: CUjit_option_enum = 13;
pub const CU_JIT_CACHE_MODE: CUjit_option_enum = 14;
pub const CU_JIT_NEW_SM3X_OPT: CUjit_option_enum = 15;
pub const CU_JIT_FAST_COMPILE: CUjit_option_enum = 16;
pub const CU_JIT_GLOBAL_SYMBOL_NAMES: CUjit_option_enum = 17;
pub const CU_JIT_GLOBAL_SYMBOL_ADDRESSES: CUjit_option_enum = 18;
pub const CU_JIT_GLOBAL_SYMBOL_COUNT: CUjit_option_enum = 19;
pub const CU_JIT_NUM_OPTIONS: CUjit_option_enum = 20;
pub type CUjit_option_enum = ::std::os::raw::c_uint;
pub use self::CUjit_option_enum as CUjit_option;
pub const CU_JIT_INPUT_CUBIN: CUjitInputType_enum = 0;
pub const CU_JIT_INPUT_PTX: CUjitInputType_enum = 1;
pub const CU_JIT_INPUT_FATBINARY: CUjitInputType_enum = 2;
pub const CU_JIT_INPUT_OBJECT: CUjitInputType_enum = 3;
pub const CU_JIT_INPUT_LIBRARY: CUjitInputType_enum = 4;
pub const CU_JIT_NUM_INPUT_TYPES: CUjitInputType_enum = 5;
pub type CUjitInputType_enum = ::std::os::raw::c_uint;
pub use self::CUjitInputType_enum as CUjitInputType;
pub const CU_EGL_FRAME_TYPE_ARRAY: CUeglFrameType = 0;
pub const CU_EGL_FRAME_TYPE_PITCH: CUeglFrameType = 1;
pub type CUeglFrameType = ::std::os::raw::c_uint;
pub const CU_EGL_COLOR_FORMAT_YUV420_PLANAR: CUeglColorFormat = 0;
pub const CU_EGL_COLOR_FORMAT_YUV420_SEMIPLANAR: CUeglColorFormat = 1;
pub const CU_EGL_COLOR_FORMAT_YVU420_SEMIPLANAR: CUeglColorFormat = 21;
pub const CU_EGL_COLOR_FORMAT_Y10V10U10_420_SEMIPLANAR: CUeglColorFormat = 23;
pub const CU_EGL_COLOR_FORMAT_Y12V12U12_420_SEMIPLANAR: CUeglColorFormat = 25;
pub type CUeglColorFormat = ::std::os::raw::c_uint;
pub const CU_D3D11_DEVICE_LIST_ALL: CUd3d11DeviceList_enum = 1;
pub const CU_D3D11_DEVICE_LIST_CURRENT_FRAME: CUd3d11DeviceList_enum = 2;
pub const CU_D3D11_DEVICE_LIST_NEXT_FRAME: CUd3d11DeviceList_enum = 3;
pub type CUd3d11DeviceList_enum = ::std::os::raw::c_uint;
pub use self::CUd3d11DeviceList_enum as CUd3d11DeviceList;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUuuid_st {
    pub bytes: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUuuid_st"][::std::mem::size_of::<CUuuid_st>() - 16usize];
    ["Alignment of CUuuid_st"][::std::mem::align_of::<CUuuid_st>() - 1usize];
    ["Offset of field: CUuuid_st::bytes"][::std::mem::offset_of!(CUuuid_st, bytes) - 0usize];
};
pub type CUuuid = CUuuid_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_MEMCPY2D_st {
    pub srcXInBytes: usize,
    pub srcY: usize,
    pub srcMemoryType: CUmemorytype,
    pub srcHost: *const ::std::os::raw::c_void,
    pub srcDevice: CUdeviceptr,
    pub srcArray: CUarray,
    pub srcPitch: usize,
    pub dstXInBytes: usize,
    pub dstY: usize,
    pub dstMemoryType: CUmemorytype,
    pub dstHost: *mut ::std::os::raw::c_void,
    pub dstDevice: CUdeviceptr,
    pub dstArray: CUarray,
    pub dstPitch: usize,
    pub WidthInBytes: usize,
    pub Height: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_MEMCPY2D_st"][::std::mem::size_of::<CUDA_MEMCPY2D_st>() - 128usize];
    ["Alignment of CUDA_MEMCPY2D_st"][::std::mem::align_of::<CUDA_MEMCPY2D_st>() - 8usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcXInBytes"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcXInBytes) - 0usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcY"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcY) - 8usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcMemoryType"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcMemoryType) - 16usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcHost"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcHost) - 24usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcDevice"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcDevice) - 32usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcArray"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcArray) - 40usize];
    ["Offset of field: CUDA_MEMCPY2D_st::srcPitch"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, srcPitch) - 48usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstXInBytes"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstXInBytes) - 56usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstY"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstY) - 64usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstMemoryType"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstMemoryType) - 72usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstHost"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstHost) - 80usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstDevice"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstDevice) - 88usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstArray"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstArray) - 96usize];
    ["Offset of field: CUDA_MEMCPY2D_st::dstPitch"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, dstPitch) - 104usize];
    ["Offset of field: CUDA_MEMCPY2D_st::WidthInBytes"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, WidthInBytes) - 112usize];
    ["Offset of field: CUDA_MEMCPY2D_st::Height"]
        [::std::mem::offset_of!(CUDA_MEMCPY2D_st, Height) - 120usize];
};
pub type CUDA_MEMCPY2D = CUDA_MEMCPY2D_st;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CUDA_RESOURCE_DESC_st {
    pub resType: CUresourcetype,
    pub res: CUDA_RESOURCE_DESC_st__bindgen_ty_1,
    pub flags: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union CUDA_RESOURCE_DESC_st__bindgen_ty_1 {
    pub array: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1,
    pub mipmap: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2,
    pub linear: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3,
    pub pitch2D: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
    pub reserved: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1 {
    pub hArray: CUarray,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1::hArray"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_1,
        hArray
    ) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2 {
    pub hMipmappedArray: CUmipmappedArray,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2::hMipmappedArray"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_2,
        hMipmappedArray
    )
        - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3 {
    pub devPtr: CUdeviceptr,
    pub format: CUarray_format,
    pub numChannels: ::std::os::raw::c_uint,
    pub sizeInBytes: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3>() - 24usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3::devPtr"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3,
        devPtr
    ) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3::format"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3,
        format
    ) - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3::numChannels"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3,
        numChannels
    )
        - 12usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3::sizeInBytes"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_3,
        sizeInBytes
    )
        - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4 {
    pub devPtr: CUdeviceptr,
    pub format: CUarray_format,
    pub numChannels: ::std::os::raw::c_uint,
    pub width: usize,
    pub height: usize,
    pub pitchInBytes: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4>() - 40usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::devPtr"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        devPtr
    ) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::format"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        format
    ) - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::numChannels"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        numChannels
    )
        - 12usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::width"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        width
    ) - 16usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::height"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        height
    ) - 24usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4::pitchInBytes"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_4,
        pitchInBytes
    )
        - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5 {
    pub reserved: [::std::os::raw::c_int; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5>() - 128usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5>() - 4usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5::reserved"][::std::mem::offset_of!(
        CUDA_RESOURCE_DESC_st__bindgen_ty_1__bindgen_ty_5,
        reserved
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1>() - 128usize];
    ["Alignment of CUDA_RESOURCE_DESC_st__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1::array"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st__bindgen_ty_1, array) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1::mipmap"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st__bindgen_ty_1, mipmap) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1::linear"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st__bindgen_ty_1, linear) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1::pitch2D"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st__bindgen_ty_1, pitch2D) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st__bindgen_ty_1::reserved"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st__bindgen_ty_1, reserved) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_RESOURCE_DESC_st"][::std::mem::size_of::<CUDA_RESOURCE_DESC_st>() - 144usize];
    ["Alignment of CUDA_RESOURCE_DESC_st"]
        [::std::mem::align_of::<CUDA_RESOURCE_DESC_st>() - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st::resType"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st, resType) - 0usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st::res"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st, res) - 8usize];
    ["Offset of field: CUDA_RESOURCE_DESC_st::flags"]
        [::std::mem::offset_of!(CUDA_RESOURCE_DESC_st, flags) - 136usize];
};
pub type CUDA_RESOURCE_DESC = CUDA_RESOURCE_DESC_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_TEXTURE_DESC_st {
    pub addressMode: [CUaddress_mode; 3usize],
    pub filterMode: CUfilter_mode,
    pub flags: ::std::os::raw::c_uint,
    pub maxAnisotropy: ::std::os::raw::c_uint,
    pub mipmapFilterMode: CUfilter_mode,
    pub mipmapLevelBias: f32,
    pub minMipmapLevelClamp: f32,
    pub maxMipmapLevelClamp: f32,
    pub borderColor: [f32; 4usize],
    pub reserved: [::std::os::raw::c_int; 12usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_TEXTURE_DESC_st"][::std::mem::size_of::<CUDA_TEXTURE_DESC_st>() - 104usize];
    ["Alignment of CUDA_TEXTURE_DESC_st"][::std::mem::align_of::<CUDA_TEXTURE_DESC_st>() - 4usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::addressMode"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, addressMode) - 0usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::filterMode"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, filterMode) - 12usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::flags"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, flags) - 16usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::maxAnisotropy"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, maxAnisotropy) - 20usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::mipmapFilterMode"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, mipmapFilterMode) - 24usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::mipmapLevelBias"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, mipmapLevelBias) - 28usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::minMipmapLevelClamp"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, minMipmapLevelClamp) - 32usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::maxMipmapLevelClamp"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, maxMipmapLevelClamp) - 36usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::borderColor"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, borderColor) - 40usize];
    ["Offset of field: CUDA_TEXTURE_DESC_st::reserved"]
        [::std::mem::offset_of!(CUDA_TEXTURE_DESC_st, reserved) - 56usize];
};
pub type CUDA_TEXTURE_DESC = CUDA_TEXTURE_DESC_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_RESOURCE_VIEW_DESC_st {
    _unused: [u8; 0],
}
pub type CUDA_RESOURCE_VIEW_DESC = CUDA_RESOURCE_VIEW_DESC_st;
pub type GLenum = ::std::os::raw::c_uint;
pub type GLuint = ::std::os::raw::c_uint;
pub type ffnv_EGLint = i32;
pub type ffnv_EGLStreamKHR = *mut ::std::os::raw::c_void;
pub const CU_GL_DEVICE_LIST_ALL: CUGLDeviceList_enum = 1;
pub const CU_GL_DEVICE_LIST_CURRENT_FRAME: CUGLDeviceList_enum = 2;
pub const CU_GL_DEVICE_LIST_NEXT_FRAME: CUGLDeviceList_enum = 3;
pub type CUGLDeviceList_enum = ::std::os::raw::c_uint;
pub use self::CUGLDeviceList_enum as CUGLDeviceList;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st {
    pub type_: CUexternalMemoryHandleType,
    pub handle: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1,
    pub size: ::std::os::raw::c_ulonglong,
    pub flags: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1 {
    pub fd: ::std::os::raw::c_int,
    pub win32: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1 {
    pub handle: *mut ::std::os::raw::c_void,
    pub name: *const ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1"][::std::mem::size_of::<
        CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
    >() - 16usize];
    ["Alignment of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1>()
            - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1::handle"][::std::mem::offset_of!(
        CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
        handle
    )
        - 0usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1::name"][::std::mem::offset_of!(
        CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
        name
    )
        - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1>() - 16usize];
    ["Alignment of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1::fd"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1, fd) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1::win32"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st__bindgen_ty_1, win32) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st"]
        [::std::mem::size_of::<CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st>() - 104usize];
    ["Alignment of CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st"]
        [::std::mem::align_of::<CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st::type_"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st, type_) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st::handle"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st, handle) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st::size"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st, size) - 24usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st::flags"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st, flags) - 32usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st::reserved"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st, reserved) - 36usize];
};
pub type CUDA_EXTERNAL_MEMORY_HANDLE_DESC = CUDA_EXTERNAL_MEMORY_HANDLE_DESC_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st {
    pub offset: ::std::os::raw::c_ulonglong,
    pub size: ::std::os::raw::c_ulonglong,
    pub flags: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st"]
        [::std::mem::size_of::<CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st>() - 88usize];
    ["Alignment of CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st"]
        [::std::mem::align_of::<CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st::offset"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st, offset) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st::size"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st, size) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st::flags"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st, flags) - 16usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st::reserved"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st, reserved) - 20usize];
};
pub type CUDA_EXTERNAL_MEMORY_BUFFER_DESC = CUDA_EXTERNAL_MEMORY_BUFFER_DESC_st;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st {
    pub type_: CUexternalSemaphoreHandleType,
    pub handle: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1,
    pub flags: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1 {
    pub fd: ::std::os::raw::c_int,
    pub win32: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1 {
    pub handle: *mut ::std::os::raw::c_void,
    pub name: *const ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1>(
        ) - 16usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1>(
        ) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1::handle"]
        [::std::mem::offset_of!(
            CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
            handle
        ) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1::name"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1__bindgen_ty_1,
        name
    )
        - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1>() - 16usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1::fd"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1, fd) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1::win32"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st__bindgen_ty_1,
        win32
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st>() - 96usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st::type_"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st, type_) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st::handle"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st, handle) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st::flags"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st, flags) - 24usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st::reserved"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st, reserved) - 28usize];
};
pub type CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC = CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st {
    pub params: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1,
    pub flags: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1 {
    pub fence: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1 {
    pub value: ::std::os::raw::c_ulonglong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1>(
        ) - 8usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<
            CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1,
        >() - 8usize];
    [
        "Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1::value",
    ][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1__bindgen_ty_1,
        value
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1>() - 72usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1::fence"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1,
        fence
    ) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1::reserved"][::std::mem::offset_of!(
        CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st__bindgen_ty_1,
        reserved
    )
        - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st"]
        [::std::mem::size_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st>() - 144usize];
    ["Alignment of CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st"]
        [::std::mem::align_of::<CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st::params"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st, params) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st::flags"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st, flags) - 72usize];
    ["Offset of field: CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st::reserved"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st, reserved) - 76usize];
};
pub type CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS = CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS_st;
pub type CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS = CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_ARRAY_DESCRIPTOR_st {
    pub Width: usize,
    pub Height: usize,
    pub Format: CUarray_format,
    pub NumChannels: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_ARRAY_DESCRIPTOR_st"]
        [::std::mem::size_of::<CUDA_ARRAY_DESCRIPTOR_st>() - 24usize];
    ["Alignment of CUDA_ARRAY_DESCRIPTOR_st"]
        [::std::mem::align_of::<CUDA_ARRAY_DESCRIPTOR_st>() - 8usize];
    ["Offset of field: CUDA_ARRAY_DESCRIPTOR_st::Width"]
        [::std::mem::offset_of!(CUDA_ARRAY_DESCRIPTOR_st, Width) - 0usize];
    ["Offset of field: CUDA_ARRAY_DESCRIPTOR_st::Height"]
        [::std::mem::offset_of!(CUDA_ARRAY_DESCRIPTOR_st, Height) - 8usize];
    ["Offset of field: CUDA_ARRAY_DESCRIPTOR_st::Format"]
        [::std::mem::offset_of!(CUDA_ARRAY_DESCRIPTOR_st, Format) - 16usize];
    ["Offset of field: CUDA_ARRAY_DESCRIPTOR_st::NumChannels"]
        [::std::mem::offset_of!(CUDA_ARRAY_DESCRIPTOR_st, NumChannels) - 20usize];
};
pub type CUDA_ARRAY_DESCRIPTOR = CUDA_ARRAY_DESCRIPTOR_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_ARRAY3D_DESCRIPTOR_st {
    pub Width: usize,
    pub Height: usize,
    pub Depth: usize,
    pub Format: CUarray_format,
    pub NumChannels: ::std::os::raw::c_uint,
    pub Flags: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_ARRAY3D_DESCRIPTOR_st"]
        [::std::mem::size_of::<CUDA_ARRAY3D_DESCRIPTOR_st>() - 40usize];
    ["Alignment of CUDA_ARRAY3D_DESCRIPTOR_st"]
        [::std::mem::align_of::<CUDA_ARRAY3D_DESCRIPTOR_st>() - 8usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::Width"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, Width) - 0usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::Height"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, Height) - 8usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::Depth"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, Depth) - 16usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::Format"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, Format) - 24usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::NumChannels"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, NumChannels) - 28usize];
    ["Offset of field: CUDA_ARRAY3D_DESCRIPTOR_st::Flags"]
        [::std::mem::offset_of!(CUDA_ARRAY3D_DESCRIPTOR_st, Flags) - 32usize];
};
pub type CUDA_ARRAY3D_DESCRIPTOR = CUDA_ARRAY3D_DESCRIPTOR_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st {
    pub offset: ::std::os::raw::c_ulonglong,
    pub arrayDesc: CUDA_ARRAY3D_DESCRIPTOR,
    pub numLevels: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st"]
        [::std::mem::size_of::<CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st>() - 120usize];
    ["Alignment of CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st"]
        [::std::mem::align_of::<CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st>() - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st::offset"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st, offset) - 0usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st::arrayDesc"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st, arrayDesc) - 8usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st::numLevels"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st, numLevels) - 48usize];
    ["Offset of field: CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st::reserved"]
        [::std::mem::offset_of!(CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st, reserved) - 52usize];
};
pub type CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC = CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC_st;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CUeglFrame_st {
    pub frame: CUeglFrame_st__bindgen_ty_1,
    pub width: ::std::os::raw::c_uint,
    pub height: ::std::os::raw::c_uint,
    pub depth: ::std::os::raw::c_uint,
    pub pitch: ::std::os::raw::c_uint,
    pub planeCount: ::std::os::raw::c_uint,
    pub numChannels: ::std::os::raw::c_uint,
    pub frameType: CUeglFrameType,
    pub eglColorFormat: CUeglColorFormat,
    pub cuFormat: CUarray_format,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union CUeglFrame_st__bindgen_ty_1 {
    pub pArray: [CUarray; 3usize],
    pub pPitch: [*mut ::std::os::raw::c_void; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUeglFrame_st__bindgen_ty_1"]
        [::std::mem::size_of::<CUeglFrame_st__bindgen_ty_1>() - 24usize];
    ["Alignment of CUeglFrame_st__bindgen_ty_1"]
        [::std::mem::align_of::<CUeglFrame_st__bindgen_ty_1>() - 8usize];
    ["Offset of field: CUeglFrame_st__bindgen_ty_1::pArray"]
        [::std::mem::offset_of!(CUeglFrame_st__bindgen_ty_1, pArray) - 0usize];
    ["Offset of field: CUeglFrame_st__bindgen_ty_1::pPitch"]
        [::std::mem::offset_of!(CUeglFrame_st__bindgen_ty_1, pPitch) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CUeglFrame_st"][::std::mem::size_of::<CUeglFrame_st>() - 64usize];
    ["Alignment of CUeglFrame_st"][::std::mem::align_of::<CUeglFrame_st>() - 8usize];
    ["Offset of field: CUeglFrame_st::frame"]
        [::std::mem::offset_of!(CUeglFrame_st, frame) - 0usize];
    ["Offset of field: CUeglFrame_st::width"]
        [::std::mem::offset_of!(CUeglFrame_st, width) - 24usize];
    ["Offset of field: CUeglFrame_st::height"]
        [::std::mem::offset_of!(CUeglFrame_st, height) - 28usize];
    ["Offset of field: CUeglFrame_st::depth"]
        [::std::mem::offset_of!(CUeglFrame_st, depth) - 32usize];
    ["Offset of field: CUeglFrame_st::pitch"]
        [::std::mem::offset_of!(CUeglFrame_st, pitch) - 36usize];
    ["Offset of field: CUeglFrame_st::planeCount"]
        [::std::mem::offset_of!(CUeglFrame_st, planeCount) - 40usize];
    ["Offset of field: CUeglFrame_st::numChannels"]
        [::std::mem::offset_of!(CUeglFrame_st, numChannels) - 44usize];
    ["Offset of field: CUeglFrame_st::frameType"]
        [::std::mem::offset_of!(CUeglFrame_st, frameType) - 48usize];
    ["Offset of field: CUeglFrame_st::eglColorFormat"]
        [::std::mem::offset_of!(CUeglFrame_st, eglColorFormat) - 52usize];
    ["Offset of field: CUeglFrame_st::cuFormat"]
        [::std::mem::offset_of!(CUeglFrame_st, cuFormat) - 56usize];
};
pub type CUeglFrame = CUeglFrame_st;
pub type CUstreamCallback = ::std::option::Option<
    unsafe extern "C" fn(
        hStream: CUstream,
        status: CUresult,
        userdata: *mut ::std::os::raw::c_void,
    ),
>;
pub type tcuInit =
    ::std::option::Option<unsafe extern "C" fn(Flags: ::std::os::raw::c_uint) -> CUresult>;
pub type tcuDriverGetVersion = ::std::option::Option<
    unsafe extern "C" fn(driverVersion: *mut ::std::os::raw::c_int) -> CUresult,
>;
pub type tcuDeviceGetCount =
    ::std::option::Option<unsafe extern "C" fn(count: *mut ::std::os::raw::c_int) -> CUresult>;
pub type tcuDeviceGet = ::std::option::Option<
    unsafe extern "C" fn(device: *mut CUdevice, ordinal: ::std::os::raw::c_int) -> CUresult,
>;
pub type tcuDeviceGetAttribute = ::std::option::Option<
    unsafe extern "C" fn(
        pi: *mut ::std::os::raw::c_int,
        attrib: CUdevice_attribute,
        dev: CUdevice,
    ) -> CUresult,
>;
pub type tcuDeviceGetName = ::std::option::Option<
    unsafe extern "C" fn(
        name: *mut ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
        dev: CUdevice,
    ) -> CUresult,
>;
pub type tcuDeviceGetUuid =
    ::std::option::Option<unsafe extern "C" fn(uuid: *mut CUuuid, dev: CUdevice) -> CUresult>;
pub type tcuDeviceGetUuid_v2 =
    ::std::option::Option<unsafe extern "C" fn(uuid: *mut CUuuid, dev: CUdevice) -> CUresult>;
pub type tcuDeviceGetLuid = ::std::option::Option<
    unsafe extern "C" fn(
        luid: *mut ::std::os::raw::c_char,
        deviceNodeMask: *mut ::std::os::raw::c_uint,
        dev: CUdevice,
    ) -> CUresult,
>;
pub type tcuDeviceGetByPCIBusId = ::std::option::Option<
    unsafe extern "C" fn(dev: *mut CUdevice, pciBusId: *const ::std::os::raw::c_char) -> CUresult,
>;
pub type tcuDeviceGetPCIBusId = ::std::option::Option<
    unsafe extern "C" fn(
        pciBusId: *mut ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
        dev: CUdevice,
    ) -> CUresult,
>;
pub type tcuDeviceComputeCapability = ::std::option::Option<
    unsafe extern "C" fn(
        major: *mut ::std::os::raw::c_int,
        minor: *mut ::std::os::raw::c_int,
        dev: CUdevice,
    ) -> CUresult,
>;
pub type tcuCtxCreate_v2 = ::std::option::Option<
    unsafe extern "C" fn(
        pctx: *mut CUcontext,
        flags: ::std::os::raw::c_uint,
        dev: CUdevice,
    ) -> CUresult,
>;
pub type tcuCtxGetCurrent =
    ::std::option::Option<unsafe extern "C" fn(pctx: *mut CUcontext) -> CUresult>;
pub type tcuCtxSetLimit =
    ::std::option::Option<unsafe extern "C" fn(limit: CUlimit, value: usize) -> CUresult>;
pub type tcuCtxPushCurrent_v2 =
    ::std::option::Option<unsafe extern "C" fn(pctx: CUcontext) -> CUresult>;
pub type tcuCtxPopCurrent_v2 =
    ::std::option::Option<unsafe extern "C" fn(pctx: *mut CUcontext) -> CUresult>;
pub type tcuCtxDestroy_v2 = ::std::option::Option<unsafe extern "C" fn(ctx: CUcontext) -> CUresult>;
pub type tcuMemAlloc_v2 = ::std::option::Option<
    unsafe extern "C" fn(dptr: *mut CUdeviceptr, bytesize: usize) -> CUresult,
>;
pub type tcuMemAllocPitch_v2 = ::std::option::Option<
    unsafe extern "C" fn(
        dptr: *mut CUdeviceptr,
        pPitch: *mut usize,
        WidthInBytes: usize,
        Height: usize,
        ElementSizeBytes: ::std::os::raw::c_uint,
    ) -> CUresult,
>;
pub type tcuMemAllocManaged = ::std::option::Option<
    unsafe extern "C" fn(
        dptr: *mut CUdeviceptr,
        bytesize: usize,
        flags: ::std::os::raw::c_uint,
    ) -> CUresult,
>;
pub type tcuMemsetD8Async = ::std::option::Option<
    unsafe extern "C" fn(
        dstDevice: CUdeviceptr,
        uc: ::std::os::raw::c_uchar,
        N: usize,
        hStream: CUstream,
    ) -> CUresult,
>;
pub type tcuMemFree_v2 = ::std::option::Option<unsafe extern "C" fn(dptr: CUdeviceptr) -> CUresult>;
pub type tcuMemcpy = ::std::option::Option<
    unsafe extern "C" fn(dst: CUdeviceptr, src: CUdeviceptr, bytesize: usize) -> CUresult,
>;
pub type tcuMemcpyAsync = ::std::option::Option<
    unsafe extern "C" fn(
        dst: CUdeviceptr,
        src: CUdeviceptr,
        bytesize: usize,
        hStream: CUstream,
    ) -> CUresult,
>;
pub type tcuMemcpy2D_v2 =
    ::std::option::Option<unsafe extern "C" fn(pcopy: *const CUDA_MEMCPY2D) -> CUresult>;
pub type tcuMemcpy2DAsync_v2 = ::std::option::Option<
    unsafe extern "C" fn(pcopy: *const CUDA_MEMCPY2D, hStream: CUstream) -> CUresult,
>;
pub type tcuMemcpyHtoD_v2 = ::std::option::Option<
    unsafe extern "C" fn(
        dstDevice: CUdeviceptr,
        srcHost: *const ::std::os::raw::c_void,
        ByteCount: usize,
    ) -> CUresult,
>;
pub type tcuMemcpyHtoDAsync_v2 = ::std::option::Option<
    unsafe extern "C" fn(
        dstDevice: CUdeviceptr,
        srcHost: *const ::std::os::raw::c_void,
        ByteCount: usize,
        hStream: CUstream,
    ) -> CUresult,
>;
pub type tcuMemcpyDtoH_v2 = ::std::option::Option<
    unsafe extern "C" fn(
        dstHost: *mut ::std::os::raw::c_void,
        srcDevice: CUdeviceptr,
        ByteCount: usize,
    ) -> CUresult,
>;
pub type tcuMemcpyDtoHAsync_v2 = ::std::option::Option<
    unsafe extern "C" fn(
        dstHost: *mut ::std::os::raw::c_void,
        srcDevice: CUdeviceptr,
        ByteCount: usize,
        hStream: CUstream,
    ) -> CUresult,
>;
pub type tcuMemcpyDtoD_v2 = ::std::option::Option<
    unsafe extern "C" fn(
        dstDevice: CUdeviceptr,
        srcDevice: CUdeviceptr,
        ByteCount: usize,
    ) -> CUresult,
>;
pub type tcuMemcpyDtoDAsync_v2 = ::std::option::Option<
    unsafe extern "C" fn(
        dstDevice: CUdeviceptr,
        srcDevice: CUdeviceptr,
        ByteCount: usize,
        hStream: CUstream,
    ) -> CUresult,
>;
pub type tcuGetErrorName = ::std::option::Option<
    unsafe extern "C" fn(error: CUresult, pstr: *mut *const ::std::os::raw::c_char) -> CUresult,
>;
pub type tcuGetErrorString = ::std::option::Option<
    unsafe extern "C" fn(error: CUresult, pstr: *mut *const ::std::os::raw::c_char) -> CUresult,
>;
pub type tcuCtxGetDevice =
    ::std::option::Option<unsafe extern "C" fn(device: *mut CUdevice) -> CUresult>;
pub type tcuDevicePrimaryCtxRetain =
    ::std::option::Option<unsafe extern "C" fn(pctx: *mut CUcontext, dev: CUdevice) -> CUresult>;
pub type tcuDevicePrimaryCtxRelease =
    ::std::option::Option<unsafe extern "C" fn(dev: CUdevice) -> CUresult>;
pub type tcuDevicePrimaryCtxSetFlags = ::std::option::Option<
    unsafe extern "C" fn(dev: CUdevice, flags: ::std::os::raw::c_uint) -> CUresult,
>;
pub type tcuDevicePrimaryCtxGetState = ::std::option::Option<
    unsafe extern "C" fn(
        dev: CUdevice,
        flags: *mut ::std::os::raw::c_uint,
        active: *mut ::std::os::raw::c_int,
    ) -> CUresult,
>;
pub type tcuDevicePrimaryCtxReset =
    ::std::option::Option<unsafe extern "C" fn(dev: CUdevice) -> CUresult>;
pub type tcuStreamCreate = ::std::option::Option<
    unsafe extern "C" fn(phStream: *mut CUstream, flags: ::std::os::raw::c_uint) -> CUresult,
>;
pub type tcuStreamQuery =
    ::std::option::Option<unsafe extern "C" fn(hStream: CUstream) -> CUresult>;
pub type tcuStreamSynchronize =
    ::std::option::Option<unsafe extern "C" fn(hStream: CUstream) -> CUresult>;
pub type tcuStreamDestroy_v2 =
    ::std::option::Option<unsafe extern "C" fn(hStream: CUstream) -> CUresult>;
pub type tcuStreamAddCallback = ::std::option::Option<
    unsafe extern "C" fn(
        hStream: CUstream,
        callback: CUstreamCallback,
        userdata: *mut ::std::os::raw::c_void,
        flags: ::std::os::raw::c_uint,
    ) -> CUresult,
>;
pub type tcuStreamWaitEvent = ::std::option::Option<
    unsafe extern "C" fn(
        hStream: CUstream,
        hEvent: CUevent,
        flags: ::std::os::raw::c_uint,
    ) -> CUresult,
>;
pub type tcuEventCreate = ::std::option::Option<
    unsafe extern "C" fn(phEvent: *mut CUevent, flags: ::std::os::raw::c_uint) -> CUresult,
>;
pub type tcuEventDestroy_v2 =
    ::std::option::Option<unsafe extern "C" fn(hEvent: CUevent) -> CUresult>;
pub type tcuEventSynchronize =
    ::std::option::Option<unsafe extern "C" fn(hEvent: CUevent) -> CUresult>;
pub type tcuEventQuery = ::std::option::Option<unsafe extern "C" fn(hEvent: CUevent) -> CUresult>;
pub type tcuEventRecord =
    ::std::option::Option<unsafe extern "C" fn(hEvent: CUevent, hStream: CUstream) -> CUresult>;
pub type tcuLaunchKernel = ::std::option::Option<
    unsafe extern "C" fn(
        f: CUfunction,
        gridDimX: ::std::os::raw::c_uint,
        gridDimY: ::std::os::raw::c_uint,
        gridDimZ: ::std::os::raw::c_uint,
        blockDimX: ::std::os::raw::c_uint,
        blockDimY: ::std::os::raw::c_uint,
        blockDimZ: ::std::os::raw::c_uint,
        sharedMemBytes: ::std::os::raw::c_uint,
        hStream: CUstream,
        kernelParams: *mut *mut ::std::os::raw::c_void,
        extra: *mut *mut ::std::os::raw::c_void,
    ) -> CUresult,
>;
pub type tcuLinkCreate = ::std::option::Option<
    unsafe extern "C" fn(
        numOptions: ::std::os::raw::c_uint,
        options: *mut CUjit_option,
        optionValues: *mut *mut ::std::os::raw::c_void,
        stateOut: *mut CUlinkState,
    ) -> CUresult,
>;
pub type tcuLinkAddData = ::std::option::Option<
    unsafe extern "C" fn(
        state: CUlinkState,
        type_: CUjitInputType,
        data: *mut ::std::os::raw::c_void,
        size: usize,
        name: *const ::std::os::raw::c_char,
        numOptions: ::std::os::raw::c_uint,
        options: *mut CUjit_option,
        optionValues: *mut *mut ::std::os::raw::c_void,
    ) -> CUresult,
>;
pub type tcuLinkComplete = ::std::option::Option<
    unsafe extern "C" fn(
        state: CUlinkState,
        cubinOut: *mut *mut ::std::os::raw::c_void,
        sizeOut: *mut usize,
    ) -> CUresult,
>;
pub type tcuLinkDestroy =
    ::std::option::Option<unsafe extern "C" fn(state: CUlinkState) -> CUresult>;
pub type tcuModuleLoadData = ::std::option::Option<
    unsafe extern "C" fn(module: *mut CUmodule, image: *const ::std::os::raw::c_void) -> CUresult,
>;
pub type tcuModuleUnload = ::std::option::Option<unsafe extern "C" fn(hmod: CUmodule) -> CUresult>;
pub type tcuModuleGetFunction = ::std::option::Option<
    unsafe extern "C" fn(
        hfunc: *mut CUfunction,
        hmod: CUmodule,
        name: *const ::std::os::raw::c_char,
    ) -> CUresult,
>;
pub type tcuModuleGetGlobal = ::std::option::Option<
    unsafe extern "C" fn(
        dptr: *mut CUdeviceptr,
        bytes: *mut usize,
        hmod: CUmodule,
        name: *const ::std::os::raw::c_char,
    ) -> CUresult,
>;
pub type tcuTexObjectCreate = ::std::option::Option<
    unsafe extern "C" fn(
        pTexObject: *mut CUtexObject,
        pResDesc: *const CUDA_RESOURCE_DESC,
        pTexDesc: *const CUDA_TEXTURE_DESC,
        pResViewDesc: *const CUDA_RESOURCE_VIEW_DESC,
    ) -> CUresult,
>;
pub type tcuTexObjectDestroy =
    ::std::option::Option<unsafe extern "C" fn(texObject: CUtexObject) -> CUresult>;
pub type tcuGLGetDevices_v2 = ::std::option::Option<
    unsafe extern "C" fn(
        pCudaDeviceCount: *mut ::std::os::raw::c_uint,
        pCudaDevices: *mut CUdevice,
        cudaDeviceCount: ::std::os::raw::c_uint,
        deviceList: CUGLDeviceList,
    ) -> CUresult,
>;
pub type tcuGraphicsGLRegisterImage = ::std::option::Option<
    unsafe extern "C" fn(
        pCudaResource: *mut CUgraphicsResource,
        image: GLuint,
        target: GLenum,
        Flags: ::std::os::raw::c_uint,
    ) -> CUresult,
>;
pub type tcuGraphicsUnregisterResource =
    ::std::option::Option<unsafe extern "C" fn(resource: CUgraphicsResource) -> CUresult>;
pub type tcuGraphicsMapResources = ::std::option::Option<
    unsafe extern "C" fn(
        count: ::std::os::raw::c_uint,
        resources: *mut CUgraphicsResource,
        hStream: CUstream,
    ) -> CUresult,
>;
pub type tcuGraphicsUnmapResources = ::std::option::Option<
    unsafe extern "C" fn(
        count: ::std::os::raw::c_uint,
        resources: *mut CUgraphicsResource,
        hStream: CUstream,
    ) -> CUresult,
>;
pub type tcuGraphicsSubResourceGetMappedArray = ::std::option::Option<
    unsafe extern "C" fn(
        pArray: *mut CUarray,
        resource: CUgraphicsResource,
        arrayIndex: ::std::os::raw::c_uint,
        mipLevel: ::std::os::raw::c_uint,
    ) -> CUresult,
>;
pub type tcuGraphicsResourceGetMappedPointer = ::std::option::Option<
    unsafe extern "C" fn(
        devPtrOut: *mut CUdeviceptr,
        sizeOut: *mut usize,
        resource: CUgraphicsResource,
    ) -> CUresult,
>;
pub type tcuImportExternalMemory = ::std::option::Option<
    unsafe extern "C" fn(
        extMem_out: *mut CUexternalMemory,
        memHandleDesc: *const CUDA_EXTERNAL_MEMORY_HANDLE_DESC,
    ) -> CUresult,
>;
pub type tcuDestroyExternalMemory =
    ::std::option::Option<unsafe extern "C" fn(extMem: CUexternalMemory) -> CUresult>;
pub type tcuExternalMemoryGetMappedBuffer = ::std::option::Option<
    unsafe extern "C" fn(
        devPtr: *mut CUdeviceptr,
        extMem: CUexternalMemory,
        bufferDesc: *const CUDA_EXTERNAL_MEMORY_BUFFER_DESC,
    ) -> CUresult,
>;
pub type tcuExternalMemoryGetMappedMipmappedArray = ::std::option::Option<
    unsafe extern "C" fn(
        mipmap: *mut CUmipmappedArray,
        extMem: CUexternalMemory,
        mipmapDesc: *const CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC,
    ) -> CUresult,
>;
pub type tcuMipmappedArrayGetLevel = ::std::option::Option<
    unsafe extern "C" fn(
        pLevelArray: *mut CUarray,
        hMipmappedArray: CUmipmappedArray,
        level: ::std::os::raw::c_uint,
    ) -> CUresult,
>;
pub type tcuMipmappedArrayDestroy =
    ::std::option::Option<unsafe extern "C" fn(hMipmappedArray: CUmipmappedArray) -> CUresult>;
pub type tcuImportExternalSemaphore = ::std::option::Option<
    unsafe extern "C" fn(
        extSem_out: *mut CUexternalSemaphore,
        semHandleDesc: *const CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC,
    ) -> CUresult,
>;
pub type tcuDestroyExternalSemaphore =
    ::std::option::Option<unsafe extern "C" fn(extSem: CUexternalSemaphore) -> CUresult>;
pub type tcuSignalExternalSemaphoresAsync = ::std::option::Option<
    unsafe extern "C" fn(
        extSemArray: *const CUexternalSemaphore,
        paramsArray: *const CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS,
        numExtSems: ::std::os::raw::c_uint,
        stream: CUstream,
    ) -> CUresult,
>;
pub type tcuWaitExternalSemaphoresAsync = ::std::option::Option<
    unsafe extern "C" fn(
        extSemArray: *const CUexternalSemaphore,
        paramsArray: *const CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS,
        numExtSems: ::std::os::raw::c_uint,
        stream: CUstream,
    ) -> CUresult,
>;
pub type tcuArrayCreate = ::std::option::Option<
    unsafe extern "C" fn(
        pHandle: *mut CUarray,
        pAllocateArray: *const CUDA_ARRAY_DESCRIPTOR,
    ) -> CUresult,
>;
pub type tcuArray3DCreate = ::std::option::Option<
    unsafe extern "C" fn(
        pHandle: *mut CUarray,
        pAllocateArray: *const CUDA_ARRAY3D_DESCRIPTOR,
    ) -> CUresult,
>;
pub type tcuArrayDestroy = ::std::option::Option<unsafe extern "C" fn(hArray: CUarray) -> CUresult>;
pub type tcuEGLStreamProducerConnect = ::std::option::Option<
    unsafe extern "C" fn(
        conn: *mut CUeglStreamConnection,
        stream: ffnv_EGLStreamKHR,
        width: ffnv_EGLint,
        height: ffnv_EGLint,
    ) -> CUresult,
>;
pub type tcuEGLStreamProducerDisconnect =
    ::std::option::Option<unsafe extern "C" fn(conn: *mut CUeglStreamConnection) -> CUresult>;
pub type tcuEGLStreamConsumerDisconnect =
    ::std::option::Option<unsafe extern "C" fn(conn: *mut CUeglStreamConnection) -> CUresult>;
pub type tcuEGLStreamProducerPresentFrame = ::std::option::Option<
    unsafe extern "C" fn(
        conn: *mut CUeglStreamConnection,
        eglframe: CUeglFrame,
        pStream: *mut CUstream,
    ) -> CUresult,
>;
pub type tcuEGLStreamProducerReturnFrame = ::std::option::Option<
    unsafe extern "C" fn(
        conn: *mut CUeglStreamConnection,
        eglframe: *mut CUeglFrame,
        pStream: *mut CUstream,
    ) -> CUresult,
>;
pub type tcuD3D11GetDevice = ::std::option::Option<
    unsafe extern "C" fn(
        device: *mut CUdevice,
        dxgiAdapter: *mut ::std::os::raw::c_void,
    ) -> CUresult,
>;
pub type tcuD3D11GetDevices = ::std::option::Option<
    unsafe extern "C" fn(
        deviceCountOut: *mut ::std::os::raw::c_uint,
        devices: *mut CUdevice,
        deviceCount: ::std::os::raw::c_uint,
        d3d11device: *mut ::std::os::raw::c_void,
        listType: CUd3d11DeviceList,
    ) -> CUresult,
>;
pub type tcuGraphicsD3D11RegisterResource = ::std::option::Option<
    unsafe extern "C" fn(
        cudaResourceOut: *mut CUgraphicsResource,
        d3d11Resource: *mut ::std::os::raw::c_void,
        flags: ::std::os::raw::c_uint,
    ) -> CUresult,
>;
