#!/usr/bin/env python3
"""Generate examples/client/keys.h: the toolkit's key codes to usage codes.

Two tables that each go one way are crossed so the result is checked by
construction: the toolkit's own Linux map takes its key code to an X key code,
which is the kernel's code plus eight; the host's usage table takes a usage
code to the kernel's code. Inverting the second and composing gives toolkit
key -> usage, and a key the two disagree on has no entry rather than a wrong
one. The result is data derived from two public tables, not transcribed from
anything.

    python3 scripts/gen-client-keys.py > examples/client/keys.h
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MATOYA_H = ROOT / "third_party/matoya/src/matoya.h"
KEYMAP_H = ROOT / "third_party/matoya/src/unix/linux/x11/keymap.h"
USAGE_RS = ROOT / "crates/inject/src/usage.rs"


def toolkit_keys():
    """MTY_KEY_* name -> value, from the toolkit's header."""
    keys = {}
    for line in MATOYA_H.read_text().splitlines():
        m = re.match(r"\s*(MTY_KEY_[A-Z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)", line)
        if m and m.group(1) not in ("MTY_KEY_MAX", "MTY_KEY_MAKE_32"):
            keys[m.group(1)] = int(m.group(2), 0)
    return keys


def toolkit_to_kernel():
    """MTY_KEY_* name -> kernel key code, from the toolkit's Linux map."""
    out = {}
    for line in KEYMAP_H.read_text().splitlines():
        m = re.match(r"\s*\[(MTY_KEY_[A-Z0-9_]+)\]\s*=\s*(\d+)", line)
        if m and int(m.group(2)) >= 8:
            out[m.group(1)] = int(m.group(2)) - 8
    return out


def kernel_to_usage():
    """Kernel key code -> usage code, the host's table inverted.

    Where two usages reach one kernel code the lower usage wins, which is the
    standard's own code for the key rather than a peer's alias of it.
    """
    text = USAGE_RS.read_text()
    body = re.search(r"const KERNEL_KEY: \[u16; 256\] = \[(.*?)\];", text, re.S).group(1)
    codes = [int(v) for v in re.findall(r"\b(\d+)\b", re.sub(r"//.*", "", body))]
    assert len(codes) == 256, len(codes)
    extra_first = int(re.search(r"const EXTRA_FIRST: u16 = (\d+);", text).group(1))
    extra_body = re.search(r"const EXTRA: \[u16; 6\] = \[(.*?)\];", text, re.S).group(1)
    extras = [int(v) for v in re.findall(r"^\s*(\d+),", extra_body, re.M)]
    inverse = {}
    for usage, code in list(enumerate(codes)) + [
        (extra_first + i, code) for i, code in enumerate(extras)
    ]:
        if code and code not in inverse:
            inverse[code] = usage
    return inverse


def main():
    keys = toolkit_keys()
    to_kernel = toolkit_to_kernel()
    to_usage = kernel_to_usage()
    table = {}
    for name, value in sorted(keys.items(), key=lambda kv: kv[1]):
        code = to_kernel.get(name)
        if code is None:
            continue
        usage = to_usage.get(code)
        if usage is None:
            print(f"no usage for {name} (kernel {code})", file=sys.stderr)
            continue
        table[name] = (value, usage)

    out = sys.stdout
    out.write("// The toolkit's key codes to usage codes. Generated by\n")
    out.write("// scripts/gen-client-keys.py from the toolkit's own Linux key map and\n")
    out.write("// the kernel's usage table; do not edit.\n")
    out.write("//\n")
    out.write("// Indexed by MTY_Key. Zero is a key with no usage code, which is not\n")
    out.write("// sent.\n\n")
    out.write("#pragma once\n\n#include <stdint.h>\n\n#include \"matoya.h\"\n\n")
    out.write("static const uint16_t KEY_USAGE[MTY_KEY_MAX] = {\n")
    for name, (value, usage) in sorted(table.items(), key=lambda kv: kv[1][0]):
        out.write(f"\t[{name}] = {usage},\n")
    out.write("};\n")
    print(f"{len(table)} keys", file=sys.stderr)


if __name__ == "__main__":
    main()
