#!/usr/bin/env bash
# Regenerate the system media framework's decoding bindings from the Windows
# SDK headers.
#
# Run by hand on Windows, never from a build script: the generated files are
# committed so that no build machine needs a C toolchain or the SDK. Run from
# a shell that sees LLVM's clang and the SDK (a Visual Studio x64 developer
# environment does):
#
#   cargo install bindgen-cli --version 0.72.1 --locked
#   scripts/gen-mf-bindings.sh
#
# As scripts/gen-d3d11-bindings.sh: the installed SDK is the source, its
# version written into the generated files; every struct carries a layout
# assertion; the interfaces are declared in their C form; nothing is linked.

set -euo pipefail

export MSYS2_ARG_CONV_EXCL='//'
py=""
for candidate in python3 python; do
    if "$candidate" -c '' 2>/dev/null; then py="$candidate"; break; fi
done
[ -n "$py" ] || { echo "no python" >&2; exit 1; }

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/crates/drivers/src/ffi/windows"
kits="${WindowsSdkDir:-C:/Program Files (x86)/Windows Kits/10/}"
version="${WindowsSDKVersion:-10.0.26100.0}"
version="${version%\\}"
version="${version%/}"
inc="$kits/Include/$version"
[ -f "$inc/um/mftransform.h" ] || { echo "no SDK headers at $inc" >&2; exit 1; }

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

cat > "$work/mf.h" <<'EOF'
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <ole2.h>
#include <mfapi.h>
#include <mftransform.h>
#include <strmif.h>
EOF

# Interfaces and structures reached only by pointer from a table the backend
# calls, never called or filled themselves: opaque, so their own tables and
# unions are not generated.
opaque=(
    'IStream|IStorage|IDispatch|IRecordInfo|ITypeInfo|IEnumSTATPROPSTG|IPropertySetStorage'
    'IMFCollection|IMFMediaEvent|IMFAsyncCallback|IMFAsyncResult'
    'PROPVARIANT|tagPROPVARIANT|SAFEARRAY|tagSAFEARRAY|BLOB|tagBLOB'
    'DECIMAL|tagDEC|CY|tagCY|BSTR_BLOB|CLIPDATA|tagCLIPDATA|VERSIONEDSTREAM|tagVersionedStream'
)
opaque_args=()
for pattern in "${opaque[@]}"; do
    opaque_args+=(--opaque-type "$pattern" --allowlist-type "$pattern")
done

echo "generating mf bindings against SDK $version"
bindgen "$work/mf.h" \
    --no-doc-comments \
    --no-prepend-enum-name \
    --merge-extern-blocks \
    --wrap-unsafe-ops \
    --raw-line "// Windows SDK $version." \
    `# The interfaces called: the decoder, the enumeration's activation` \
    `# objects, the media types and attributes, the samples and their` \
    `# buffers, and the codec interface a decoder's settings go through.` \
    --allowlist-type 'IMF(Transform|Activate|Attributes|MediaType|Sample|MediaBuffer)' \
    --allowlist-type 'ICodecAPI|IUnknown' \
    `# The structures the calls take, and a setting's value.` \
    --allowlist-type 'MFT_(REGISTER_TYPE_INFO|OUTPUT_DATA_BUFFER|OUTPUT_STREAM_INFO|INPUT_STREAM_INFO)' \
    --allowlist-type 'MFVideoArea|MFOffset|VARIANT|VARENUM' \
    `# Flags and messages passed as plain integers.` \
    --allowlist-type 'MFT_MESSAGE_TYPE|_MFT_ENUM_FLAG|_MFT_OUTPUT_STREAM_INFO_FLAGS|_MFNominalRange' \
    --allowlist-var 'MF_SDK_VERSION|MF_API_VERSION|MFSTARTUP_NOSOCKET|COINIT_MULTITHREADED' \
    "${opaque_args[@]}" \
    -o "$out/mf.rs" \
    -- --target=x86_64-pc-windows-msvc

# Identifiers and result codes, transcribed mechanically from the header text:
# the headers declare the identifiers as external objects only an import
# library defines, and the codes as casts no binding generator evaluates.
echo "generating mf identifiers"
"$py" - "$inc" "$out/mf_guids.rs" "$version" <<'PY'
import re
import sys

inc, dst, version = sys.argv[1], sys.argv[2], sys.argv[3]

def read(rel):
    return open(inc + "/" + rel, encoding="utf-8", errors="replace").read()

lines = [
    "// Generated by scripts/gen-mf-bindings.sh. Do not edit.",
    "// Windows SDK %s." % version,
    "",
    "use super::mf::{GUID, HRESULT};",
    "",
]

def emit(name, d1, d2, d3, octets):
    if len(octets) != 8:
        raise SystemExit("guid %s has %d octets, expected 8" % (name, len(octets)))
    lines.append("pub const %s: GUID = GUID {" % name)
    lines.append("    Data1: 0x%08x," % d1)
    lines.append("    Data2: 0x%04x," % d2)
    lines.append("    Data3: 0x%04x," % d3)
    lines.append("    Data4: [%s]," % ", ".join("0x%02x" % o for o in octets))
    lines.append("};")

def from_text(name, text):
    h = text.replace("-", "")
    emit(name, int(h[0:8], 16), int(h[8:12], 16), int(h[12:16], 16),
         [int(h[i:i + 2], 16) for i in range(16, 32, 2)])

def from_parts(name, parts):
    vals = [int(p.strip().rstrip("uUlL"), 0) for p in parts]
    emit(name, vals[0], vals[1], vals[2], vals[3:])

count = 0

# Interfaces, by their declared identifier.
for header, name in [("um/mftransform.h", "IMFTransform"), ("um/strmif.h", "ICodecAPI")]:
    m = re.search(r'MIDL_INTERFACE\("([0-9A-Fa-f-]{36})"\)\s*\n\s*%s\s*:' % name, read(header))
    if not m:
        raise SystemExit("no identifier for %s in %s" % (name, header))
    from_text("IID_" + name, m.group(1))
    count += 1

# Attribute and category identifiers declared with DEFINE_GUID.
mfapi = read("um/mfapi.h")
for name in ["MFT_CATEGORY_VIDEO_DECODER", "MFMediaType_Video", "MF_MT_MAJOR_TYPE",
             "MF_MT_SUBTYPE", "MF_MT_FRAME_SIZE", "MF_MT_DEFAULT_STRIDE",
             "MF_MT_MINIMUM_DISPLAY_APERTURE", "MF_MT_VIDEO_NOMINAL_RANGE", "MF_LOW_LATENCY"]:
    m = re.search(r"DEFINE_GUID\(\s*%s\s*,([^)]*)\)" % name, mfapi)
    if not m:
        raise SystemExit("no identifier for %s" % name)
    from_parts(name, m.group(1).split(","))
    count += 1

# The formats, declared by their four characters.
for name, fcc in [("MFVideoFormat_H264", "H264"), ("MFVideoFormat_HEVC", "HEVC"),
                  ("MFVideoFormat_NV12", "NV12"), ("MFVideoFormat_P010", "P010")]:
    if not re.search(r"DEFINE_MEDIATYPE_GUID\(\s*%s\s*,\s*FCC\('%s'\)\s*\)" % (name, fcc), mfapi):
        raise SystemExit("no format %s" % name)
    code = sum(ord(c) << (8 * i) for i, c in enumerate(fcc))
    emit(name, code, 0x0000, 0x0010, [0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71])
    count += 1

# The enumeration's attributes, declared as constant objects.
mft = read("um/mftransform.h")
for name in ["MFT_TRANSFORM_CLSID_Attribute", "MFT_FRIENDLY_NAME_Attribute"]:
    m = re.search(r"GUID\s+%s\s*=\s*\{\s*([^{]*)\{([^}]*)\}\s*\}" % name, mft)
    if not m:
        raise SystemExit("no identifier for %s" % name)
    from_parts(name, m.group(1).rstrip().rstrip(",").split(",") + m.group(2).split(","))
    count += 1

# The codec settings.
codecapi = read("um/codecapi.h")
for name in ["AVDecNumWorkerThreads"]:
    m = re.search(r'DEFINE_CODECAPI_GUID\(\s*%s\s*,\s*"([0-9A-Fa-f-]{36})"' % name, codecapi)
    if not m:
        raise SystemExit("no codec setting %s" % name)
    from_text("CODECAPI_" + name, m.group(1))
    count += 1

# The system's own H.264 decoder, by its class.
m = re.search(r'DECLSPEC_UUID\("([0-9A-Fa-f-]{36})"\)\s*\n\s*CMSH264DecoderMFT', read("um/wmcodecdsp.h"))
if not m:
    raise SystemExit("no class for CMSH264DecoderMFT")
from_text("CLSID_CMSH264DecoderMFT", m.group(1))
count += 1

if count < 19:
    raise SystemExit("only %d identifiers matched; the header layout changed" % count)

# The result codes the decoder answers.
mferror = read("um/mferror.h")
lines.append("")
for name in ["MF_E_TRANSFORM_NEED_MORE_INPUT", "MF_E_TRANSFORM_STREAM_CHANGE",
             "MF_E_TRANSFORM_TYPE_NOT_SET", "MF_E_NOTACCEPTING", "MF_E_NO_MORE_TYPES",
             "MF_E_INVALIDMEDIATYPE", "MF_E_BUFFERTOOSMALL", "MF_E_ATTRIBUTENOTFOUND",
             "MF_E_MEDIA_EXTENSION_PACKAGE_LICENSE_INVALID"]:
    m = re.search(r"#define\s+%s\s+_HRESULT_TYPEDEF_\((0x[0-9A-Fa-f]{8})L\)" % name, mferror)
    if not m:
        raise SystemExit("no code %s" % name)
    lines.append("pub const %s: HRESULT = 0x%s_u32 as HRESULT;" % (name, m.group(1)[2:].upper()))

open(dst, "w", encoding="ascii", newline="\n").write("\n".join(lines) + "\n")
print("  %d identifiers" % count)
PY

rustfmt --edition 2024 "$out/mf.rs" "$out/mf_guids.rs"
