#!/usr/bin/env bash
# Regenerate the encoder FFI bindings from the vendored headers.
#
# Run by hand, never from a build script: the generated files are committed so
# that no build machine needs a C toolchain. See third_party/nvcodec/PROVENANCE.md.
#
#   sudo apt-get install libclang-dev
#   cargo install bindgen-cli --locked
#   scripts/gen-nvenc-bindings.sh
#
# Then build. Every struct carries a compile-time layout assertion derived from
# the header, so a mismatch is a build failure rather than a runtime surprise.

set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
inc="$root/third_party/nvcodec/include"
out="$root/crates/encode/src/ffi"
enc_h="$inc/ffnvcodec/nvEncodeAPI.h"
cuda_h="$inc/ffnvcodec/dynlink_cuda.h"

mkdir -p "$out"

# No doc comments: the vendored header is where documentation lives, and
# doxygen text carried into a .rs file breaks the ASCII gate, which covers
# crates/ but not third_party/.
common=(
    --no-doc-comments
    --no-prepend-enum-name
    --merge-extern-blocks
)

# Types and enum constants only. Functions are deliberately excluded: the
# library is opened at runtime so its absence is a missing backend rather than
# a failed start, which an extern block would turn into a link dependency.
#
# The GUID objects are excluded for a sharper reason. They are `static const`
# in the header, so no exported symbol exists for them in any library; bindgen
# renders each one as an extern static, which is a reference that can never
# resolve. They are generated from the header text below instead.
echo "generating nvenc bindings"
bindgen "$enc_h" \
    "${common[@]}" \
    --allowlist-type '_?NV_?ENC.*' \
    --allowlist-type 'GUID' \
    --allowlist-var 'NV_?ENC.*' \
    --blocklist-item '.*_GUID' \
    -o "$out/nvenc.rs" \
    -- -I "$inc"

# The CUDA header declares function pointer typedefs rather than functions, so
# it is already shaped for runtime loading and needs no exclusions.
echo "generating cuda bindings"
bindgen "$cuda_h" \
    "${common[@]}" \
    --allowlist-type 'CU.*' \
    --allowlist-type 'tcu.*' \
    --allowlist-var 'CU.*' \
    -o "$out/cuda.rs" \
    -- -I "$inc"

# Codec, preset, profile and tuning identifiers, transcribed mechanically from
# the header so that no human copies sixteen bytes of hex.
echo "generating guid constants"
python3 - "$enc_h" "$out/guids.rs" <<'PY'
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
text = open(src, encoding="utf-8", errors="replace").read()

pattern = re.compile(
    r"static\s+const\s+GUID\s+(\w+)\s*=\s*\{\s*"
    r"(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*,\s*\{\s*"
    r"([^}]+)\}\s*\}\s*;",
    re.MULTILINE,
)

lines = [
    "// Generated by scripts/gen-nvenc-bindings.sh. Do not edit.",
    "//",
    "// These are `static const` in the header rather than exported symbols, so",
    "// they cannot be linked against and are emitted as constants instead.",
    "",
    "use super::nvenc::GUID;",
    "",
]

count = 0
for name, d1, d2, d3, rest in pattern.findall(text):
    octets = [b.strip() for b in rest.split(",") if b.strip()]
    if len(octets) != 8:
        raise SystemExit("guid %s has %d octets, expected 8" % (name, len(octets)))
    lines.append("pub const %s: GUID = GUID {" % name)
    lines.append("    Data1: %s," % d1)
    lines.append("    Data2: %s," % d2)
    lines.append("    Data3: %s," % d3)
    lines.append("    Data4: [%s]," % ", ".join(octets))
    lines.append("};")
    count += 1

if count == 0:
    raise SystemExit("no GUIDs matched; the header layout changed")

open(dst, "w", encoding="ascii").write("\n".join(lines) + "\n")
print("  %d identifiers" % count)
PY

# bindgen's own formatting does not match this workspace's, and the generated
# files are committed, so the format gate would fail after every regeneration.
echo "formatting"
cargo fmt -p lowlat-encode

echo "done. build to check the layout assertions."
