#!/usr/bin/env bash
# Compile the plane split's compute shaders (crates/decode/src/d3d11_split.hlsl)
# and write their bytecode as Rust constants beside it.
#
# Run by hand on Windows, never from a build script: the bytecode is committed
# so that no build machine needs the shader compiler, and nothing compiles a
# shader at run time. Run from a shell that sees the SDK's `fxc` (a Visual
# Studio x64 developer environment does):
#
#   scripts/gen-d3d11-split.sh
#
# The compiler's banner is written into the generated file's first lines, so a
# regeneration with another one shows in the diff.

set -euo pipefail

# Git Bash rewrites arguments that look like paths, and the compiler's options
# begin with "/"; every path handed to a native program is converted by hand.
export MSYS2_ARG_CONV_EXCL='*'
py=""
for candidate in python3 python; do
    if "$candidate" -c '' 2>/dev/null; then py="$candidate"; break; fi
done
[ -n "$py" ] || { echo "no python" >&2; exit 1; }

root="$(cd "$(dirname "$0")/.." && pwd)"
src="$root/crates/decode/src/d3d11_split.hlsl"
out="$root/crates/decode/src/d3d11_split.rs"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# The whole help is read, so the compiler never writes into a closed pipe.
banner="$( (fxc /? 2>&1 || true) | sed -n 1p | tr -d '\r')"
echo "compiling the split with: $banner"
variants=(PLANAR8 PLANAR16 VUYA Y410)
for v in "${variants[@]}"; do
    fxc /nologo /T cs_5_0 /E main /O3 /WX /Qstrip_debug /Qstrip_reflect /Qstrip_priv \
        /D "$v=1" /Fo "$(cygpath -w "$work/$v.cso")" "$(cygpath -w "$src")" >/dev/null
done

# The interpreter may be a native one, which reads native paths only.
"$py" - "$(cygpath -w "$work")" "$(cygpath -w "$out")" "$banner" "${variants[@]}" <<'PY'
import sys

work, dst, banner, variants = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4:]
names = {
    "PLANAR8": "the two-plane layout at eight bits",
    "PLANAR16": "the two-plane layout at ten bits in sixteen",
    "VUYA": "the packed full-chroma layout at eight bits",
    "Y410": "the packed full-chroma layout at ten bits",
}
lines = [
    "// Generated by scripts/gen-d3d11-split.sh from d3d11_split.hlsl. Do not edit.",
    "// %s." % banner,
    "",
]
for v in variants:
    code = open("%s/%s.cso" % (work, v), "rb").read()
    lines.append("/// The split for %s." % names[v])
    lines.append("pub(super) const %s: &[u8] = &[" % v)
    for i in range(0, len(code), 16):
        lines.append("    " + " ".join("0x%02x," % b for b in code[i:i + 16]))
    lines.append("];")
    lines.append("")
open(dst, "w", encoding="ascii", newline="\n").write("\n".join(lines))
print("  %d variants" % len(variants))
PY

rustfmt --edition 2024 "$(cygpath -w "$out")"
